import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
const db=new PGlite();
const user='10000000-0000-4000-8000-000000000001', other='10000000-0000-4000-8000-000000000002', project='20000000-0000-4000-8000-000000000001';
await db.exec(`create role authenticated; create role anon; create role service_role; create schema auth;
create table auth.users(id uuid primary key); insert into auth.users values('${user}'),('${other}');
create table public.projects(id uuid primary key,is_deleted boolean default false); insert into projects values('${project}',false);
create table public.email_messages(id uuid,subject text); create table public.llm_telemetry(id uuid,cost_usd numeric);`);
if(!process.argv.includes('--before-fix')) await db.exec(await readFile(new URL('../../migrations/20261008235532_private_atomic_edge_operation_quotas.sql',import.meta.url),'utf8'));
let passed=0,failed=0;
const scalar=async(sql,p=[]) => (await db.query(sql,p)).rows[0]?.result;
const reserve=(key='request-1',options={})=>scalar('select public.reserve_edge_operation($1,$2,$3,$4,$5,$6,$7,$8) result',[
  options.kind??'email-send',Object.hasOwn(options,'user')?options.user:user,options.project??project,key.padEnd(8,'.'),options.hash??'a'.repeat(64),options.count??1,options.cap??0,options.cost??0]);
const finish=(id,state='completed',cost=null,result={success:true})=>scalar('select public.finish_edge_operation($1,$2,$3,$4,$5) result',[id,state,cost,result,200]);
async function check(name,fn){await db.exec('reset role; begin');try{await fn();passed++;console.log(`PASS ${name}`);}catch(e){failed++;console.error(`FAIL ${name}: ${e.message}`);}finally{await db.exec('rollback; reset role');}}
async function denied(sql,p=[]){await db.exec('savepoint denied');await assert.rejects(db.query(sql,p));await db.exec('rollback to savepoint denied');}
try {
 await check('cap one admits one of concurrently submitted independent operations',async()=>{const outcomes=await Promise.all([reserve('one'),reserve('two')]);assert.equal(outcomes.filter(x=>x.decision==='reserved').length,1);assert.equal(outcomes.filter(x=>x.decision==='limited').length,1);});
 await check('every contender writes the scope revision before counting, fencing stale snapshots',async()=>{await reserve();await reserve('other');assert.equal(await scalar('select revision::int result from steelbuild_edge_private.scopes'),2);});
 await check('deleting/editing correspondence or telemetry cannot reset reservations',async()=>{await reserve();await db.exec("delete from email_messages; delete from llm_telemetry");assert.equal((await reserve('next')).decision,'limited');});
 await check('same key cannot dispatch again while pending',async()=>{const first=await reserve();const repeat=await reserve();assert.equal(repeat.decision,'pending');assert.equal(repeat.operation_id,first.operation_id);});
 await check('changed payload with the same key is rejected',async()=>{await reserve();assert.equal((await reserve('request-1',{hash:'b'.repeat(64)})).decision,'conflict');});
 await check('completed result is replayed without a new quota charge',async()=>{const first=await reserve();await finish(first.operation_id);const again=await reserve();assert.equal(again.decision,'replay');assert.deepEqual(again.result,{success:true});assert.equal((await reserve('other')).decision,'limited');});
 await check('unknown provider outcome never automatically expires into redispatch',async()=>{const first=await reserve();await finish(first.operation_id,'unknown',null,null);await db.exec("update steelbuild_edge_private.operations set created_at=now()-interval '2 days'");assert.equal((await reserve()).decision,'unknown');assert.equal((await reserve('new')).decision,'reserved');});
 await check('expired response payload does not permit the same operation again',async()=>{const first=await reserve();await finish(first.operation_id);await db.exec("update steelbuild_edge_private.operations set created_at=now()-interval '2 days'");const again=await reserve();assert.equal(again.decision,'completed');assert.equal(again.result,null);});
 await check('maintenance purge clears expired response bodies but preserves tombstones and recent responses',async()=>{const first=await reserve('old',{count:0});await finish(first.operation_id);await db.exec("update steelbuild_edge_private.operations set created_at=now()-interval '2 days'");const recent=await reserve('recent',{count:0});await finish(recent.operation_id);assert.equal(await scalar('select public.purge_edge_operation_results(500) result'),1);assert.equal(await scalar('select count(*)::int result from steelbuild_edge_private.operations'),2);assert.equal((await reserve('old',{count:0})).decision,'completed');assert.equal((await reserve('recent',{count:0})).decision,'replay');});
 await check('reserved cost blocks overlapping work then known usage releases unused capacity',async()=>{const first=await reserve('llm-a',{kind:'llm-proxy',count:0,cap:1,cost:.8});assert.equal((await reserve('llm-b',{kind:'llm-proxy',count:0,cap:1,cost:.8})).decision,'limited');await finish(first.operation_id,'completed',.1);assert.equal((await reserve('llm-b',{kind:'llm-proxy',count:0,cap:1,cost:.8})).decision,'reserved');});
 await check('missing usage retains the full reserved cost',async()=>{const first=await reserve('llm-a',{kind:'llm-proxy',count:0,cap:1,cost:.8});await finish(first.operation_id,'completed',null);assert.equal((await reserve('llm-b',{kind:'llm-proxy',count:0,cap:1,cost:.3})).decision,'limited');});
 await check('different users have independent send budgets',async()=>{await reserve();assert.equal((await reserve('request-1',{user:other})).decision,'reserved');});
 await check('classifier budget is per project, independent of editable telemetry',async()=>{await reserve('classify-1',{kind:'email-classify',user:null});assert.equal((await reserve('classify-2',{kind:'email-classify',user:null})).decision,'limited');});
 await check('archived project cannot reserve an operation',async()=>{await db.exec('update projects set is_deleted=true');await denied('select public.reserve_edge_operation($1,$2,$3,$4,$5,1,0,0)',['email-send',user,project,'one','a'.repeat(64)]);});
 await check('deleting a project clears replay content but retains user accounting',async()=>{const first=await reserve();await finish(first.operation_id);await db.exec('delete from projects');assert.equal(await scalar('select result is null result from steelbuild_edge_private.operations'),true);assert.equal(await scalar('select count(*)::int result from steelbuild_edge_private.operations'),1);});
 await check('late provider completion cannot restore erased project output',async()=>{const first=await reserve();await db.exec('delete from projects');assert.equal(await finish(first.operation_id),true);assert.equal(await scalar('select result is null result from steelbuild_edge_private.operations'),true);});
 await check('account deletion erases user operation records',async()=>{await reserve();await db.query('delete from auth.users where id=$1',[user]);assert.equal(await scalar('select count(*)::int result from steelbuild_edge_private.operations'),0);});
 await check('finish is immutable and cannot refund a completed operation twice',async()=>{const first=await reserve('llm-a',{kind:'llm-proxy',count:0,cap:1,cost:.8});assert.equal(await finish(first.operation_id,'completed',.5),true);assert.equal(await finish(first.operation_id,'completed',0),false);assert.equal((await reserve('llm-b',{kind:'llm-proxy',count:0,cap:1,cost:.6})).decision,'limited');});
 await check('ledger failure rolls back and does not grant provider dispatch',async()=>{await db.exec("create function steelbuild_edge_private.fail_insert() returns trigger language plpgsql as $$ begin raise exception 'synthetic ledger unavailable'; end $$; create trigger fail_insert before insert on steelbuild_edge_private.operations for each row execute function steelbuild_edge_private.fail_insert()");await denied('select public.reserve_edge_operation($1,$2,$3,$4,$5,1,0,0)',['email-send',user,project,'one','a'.repeat(64)]);assert.equal(await scalar('select count(*)::int result from steelbuild_edge_private.operations'),0);});
 for(const role of ['anon','authenticated']) await check(`${role} cannot inspect/edit ledger or reserve/settle usage`,async()=>{await db.exec(`set role ${role}`);await denied('select * from steelbuild_edge_private.operations');await denied('select public.reserve_edge_operation($1,$2,$3,$4,$5,1,0,0)',['email-send',user,project,'one','a'.repeat(64)]);await denied('select public.finish_edge_operation($1,$2,null,null,200)',[user,'unknown']);await denied('select public.purge_edge_operation_results(500)');});
 await check('service-only RPC works without direct private-table grants',async()=>{await db.exec('set role service_role');assert.equal((await reserve()).decision,'reserved');await denied('delete from steelbuild_edge_private.operations');});
 for(const [count,cap,cost] of [[-1,0,0],[1,-1,0],[1,0,-1],[1,'NaN',0],[1,0,'Infinity']])await check(`invalid caps/reservations fail closed ${count}/${cap}/${cost}`,async()=>{await denied('select public.reserve_edge_operation($1,$2,$3,$4,$5,$6,$7,$8)',['email-send',user,project,'one','a'.repeat(64),count,cap,cost]);});
}finally{await db.close();}
console.log(`${passed} passed; ${failed} failed`);if(failed)process.exitCode=1;
