import { useState } from "react";
import { PLANS } from "@/lib/billing/plans";
import "@/styles/marketing-landing.css";
const screens = [
    { name: "project-dashboard", label: "Project overview", title: "Know where the project stands.", text: "See project health, open decisions, and production readiness together. Give your team a clear place to start the day.", detail: "Project health · Open RFIs · Piece control" },
    { name: "drawing-control", label: "Drawing control", title: "Keep the next approval moving.", text: "Follow drawing sets, revisions, and approval stages. See who needs to act and what has to happen before steel can move.", detail: "Drawing sets · Revisions · Approval stages" },
    { name: "rfi-control", label: "RFIs & actions", title: "Put every question in the right hands.", text: "Keep the question, responsible party, required date, and next action together so unresolved items stay visible.", detail: "Ball in court · Aging · Response ownership" },
    { name: "fab-release", label: "Fabrication release", title: "See what is holding up the shop.", text: "Bring release gates, blocked packages, and fabrication commitments into one view before the next handoff.", detail: "Release gates · Blockers · Shop commitments" },
    { name: "work-packages", label: "Work packages", title: "Connect the work from detail to field.", text: "Follow package readiness across detailing, fabrication, delivery, and erection, with exceptions surfaced for the team.", detail: "Detailing · Fabrication · Delivery · Erection" },
    { name: "piece-register", label: "Piece tracking", title: "Keep the steel in sight.", text: "Track pieces through the production lifecycle and see counts, progress, and exceptions in the same record.", detail: "Piece counts · Production stages · Exceptions" },
];
const demo = "mailto:n.lortz1987@gmail.com?subject=SteelBuild-Pro%20Demo";
const plans = PLANS.map(plan => ({ name: plan.name, price: plan.priceMonthly ? "$" + plan.priceMonthly : "Free", copy: plan.blurb, features: plan.features }));
const roles = [
    { name: "GCs", title: "Keep the steel scope off the critical path.", pain: "An unanswered RFI or late approval can stop the next trade.", workflow: "Follow drawing reviews, response ownership, and release readiness in the same project record.", track: "Track open RFIs, overdue responses, and approval stages.", screen: "rfi-control" },
    { name: "Fabricators & erectors", title: "Know what is ready before it reaches the shop.", pain: "A package marked urgent is not always ready to fabricate or erect.", workflow: "Connect drawing status, release gates, package readiness, and production progress.", track: "Track blocked packages, released work, and piece status.", screen: "fab-release" },
    { name: "Subcontractors", title: "Give every handoff a clear owner.", pain: "Requests spread across calls, emails, and spreadsheets lose their next step.", workflow: "Keep RFIs, submittals, drawing revisions, and work packages tied to the project.", track: "Track required dates, ball in court, and readiness exceptions.", screen: "work-packages" },
    { name: "Owners / developers", title: "See the decisions behind the project status.", pain: "A progress update is only useful when you can see what is holding the work up.", workflow: "Use project oversight to follow open decisions and production readiness with the delivery team.", track: "Track project health, outstanding approvals, and production counts.", screen: "project-dashboard" },
];
const questions = [
    [
        "We already have spreadsheets and Tekla EPM. Where does SteelBuild-Pro fit?",
        "Start with the handoffs that are hardest to track: which drawing is current, who owes an RFI response, and whether a package is ready for fabrication. SteelBuild-Pro brings those records together with work packages and piece status. You can bring in supported Tekla EPM and drawing-log exports without rebuilding every project record by hand."
    ],
    [
        "A revised drawing just landed. How do we keep the shop on the right revision?",
        "Keep the revision with its drawing set, follow its review stage, and check the RFIs tied to that work. A new upload and a fabrication release are separate decisions. Your team can review the current sheets and outstanding questions before releasing the affected package, with the earlier revisions still available in the project record."
    ],
    [
        "What tells us a package is actually ready to fabricate?",
        "The release workflow checks the drawing information and unresolved items tied to the work, including open RFIs and drawing release status. That gives the team a concrete list to resolve before a shop handoff. Pro includes fabrication release and production status; your team still owns the approval and release decision."
    ],
    [
        "Can we bring over an existing drawing log?",
        "Yes. Supported Tekla EPM and drawing-log imports are included on every plan, including Free. Start with a current export and review the imported records before using them to run the job. If your company uses a custom spreadsheet, bring a sample to the demo so we can check its columns and confirm the import path."
    ],
    [
        "What can a foreman do when the jobsite loses signal?",
        "Field Today on Pro supports offline task-progress updates, punch items, and photo capture. Pending items stay in an outbox for syncing when the connection returns. Open the project while you have signal, and check that the outbox clears afterward. Drawing downloads and the rest of the application should not be treated as fully available offline."
    ],
    [
        "Do we have to move every project over at once?",
        "Start with one active job and one clear problem, such as drawing revisions or unanswered RFIs. Create the workspace, add a teammate, and bring in the records for that job. Use that first project to agree on who updates each record and who makes release decisions before expanding to the rest of the team."
    ],
    [
        "What can we actually run on Free, and when would we need Pro?",
        "Free has no time limit and includes one project, two members, drawings, submittals, RFIs, and supported imports. Pro adds fabrication release, production status, deliveries, pay applications, backcharges, and Field Today, with room for 10 projects and 15 members. Upgrade when you need those workflows or more capacity."
    ],
    [
        "Will the price climb every time we add someone?",
        "Plans are priced per workspace. Pro is $99 per month for up to 10 projects and 15 members. Business is $299 per month with unlimited projects and members, all modules, and priority support. Everyone in the workspace shares its plan limits; pending invitations count toward the member limit too."
    ]
];
function Ctas({ onStart }: {
    onStart: () => void;
}) { return <div className="hero-actions"><button type="button" className="button button-primary" onClick={onStart}>Start free <span aria-hidden="true">↗︎</span></button><a className="button button-secondary" href={demo}>Book a demo <span aria-hidden="true">↗︎</span></a></div>; }
function Logo() { return <a className="logo" href="#top" aria-label="SteelBuild-Pro home"><img src="/marketing/steelbuild-pro-logo.jpg" alt="SteelBuild Pro steel diamond badge" width="1248" height="832"/></a>; }
function Capture({ name, label }: {
    name: string;
    label: string;
}) { return <figure className="product-frame"><div className="frame-top"><span><i /><i /><i /></span><b>STEELBUILD-PRO / {label.toUpperCase()}</b></div><a href={`/marketing/product/${name}.png`} target="_blank" rel="noopener noreferrer" aria-label={`View full-size ${label} screenshot (opens new tab)`}><div className="screen-viewport"><img src={`/marketing/product/${name}.png`} alt={`Actual SteelBuild-Pro ${label} screen`} loading="lazy"/></div></a><figcaption>Actual app screen <span>Open full size ↗︎</span></figcaption></figure>; }
export default function MarketingLanding({ onStart, onLogin }: {
    onStart: () => void;
    onLogin: () => void;
}) {
    const [selected, setSelected] = useState(0);
    const [role, setRole] = useState(1);
    const screen = screens[selected];
    const activeRole = roles[role];
    return <main className="marketing-landing">
    <header className="site-header"><div className="brand-lockup"><Logo /><span>Built for people<br />who build.</span></div><nav aria-label="Main navigation"><a href="#platform">Product</a><a href="#solutions">Solutions</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></nav><div className="header-actions"><button type="button" className="sign-in" onClick={onLogin}>Log in</button><button type="button" className="button button-primary" onClick={onStart}>Start free <span aria-hidden="true">↗︎</span></button></div></header>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><span /> PROJECT CONTROLS FOR STEEL CONSTRUCTION</p><h1>Steel construction.<br /><em>One connected<br />operation.</em></h1><p className="hero-description">Bring the office, shop, and field onto one project record—with drawings, RFIs, and release decisions connected to the work.</p><Ctas onStart={onStart}/><div className="hero-proof"><span>Free without a time limit</span><span>1 project · 2 members</span></div></div><img className="hero-background" src="/marketing/photos/steel-frame-960.webp" srcSet="/marketing/photos/steel-frame-480.webp 480w, /marketing/photos/steel-frame-960.webp 960w, /marketing/photos/steel-frame-1600.webp 1600w, /marketing/photos/steel-frame-2400.webp 2400w" sizes="100vw" alt="Exposed steel columns and beams of a high-rise under construction beside tower cranes, photographed by Jacek Dylag" loading="eager" width="2400" height="3600"/><div className="hero-baseline"><strong>Built for people who build.</strong><p>FROM THE FIRST DRAWING<br />TO THE LAST PIECE.</p><a href="#problem" aria-label="Continue to project challenges">↓</a></div></section>
    <section className="problem-section section-wrap" id="problem"><div className="section-heading"><div><p className="eyebrow">THE COST OF DISCONNECTED WORK</p><h2>The work is hard enough.<br />The information shouldn’t be.</h2></div><p>Steel does not move because a spreadsheet says it should. It moves when the right drawing, answer, and release reach the right person.</p></div><div className="pain-grid">{[["01", "Disconnected teams", "The office, shop, and field work from different updates. Every handoff becomes another round of calls."], ["02", "Stale drawings in the field", "A revision gets missed. The crew works from yesterday’s information, and rework follows."], ["03", "Fire-drill closeouts", "Decisions and supporting records are scattered. The team loses time reconstructing what happened."]].map(([n, title, text]) => <article key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div><Ctas onStart={onStart}/></section>
    <section className="product-section section-wrap" id="platform"><div className="section-heading"><div><p className="eyebrow">THE PRODUCT / REAL WORK, IN VIEW</p><h2>Give every decision<br />somewhere to land.</h2></div><p>Explore the actual SteelBuild-Pro interface. These are project screens, with the details your team needs to move the work forward.</p></div><div className="product-selector" aria-label="Explore product screens">{screens.map((s, i) => <button key={s.name} type="button" aria-pressed={selected === i} aria-controls="product-preview" onClick={() => setSelected(i)}><span>0{i + 1}</span>{s.label}</button>)}</div><div className="product-explorer" id="product-preview"><div className="product-description"><span className="screen-number">0{selected + 1} / 06</span><h3>{screen.title}</h3><p>{screen.text}</p><div className="screen-detail">{screen.detail}</div><Ctas onStart={onStart}/><span className="capture-note">Actual SteelBuild-Pro interface</span></div><Capture name={screen.name} label={screen.label}/></div>
    <div className="pillars"><p className="eyebrow">THREE JOBS. ONE PROJECT RECORD.</p>{[
            { n: "01", title: "Plan & coordinate", text: "Replace disconnected approval updates with a shared view of the next decision.", name: "drawing-control", label: "Drawing control", points: [["Drawing control", "Follow sets, revisions, and approval stages."], ["RFIs & submittals", "Keep the required response and responsible party together."], ["Readiness", "See the information that still stands between the drawing and the shop."]] },
            { n: "02", title: "Release & execute", text: "Turn approved information into work the shop and field can act on.", name: "work-packages", label: "Work packages", points: [["Fabrication release", "Surface blocked packages before the release handoff."], ["Production & delivery", "Follow package and piece status as steel moves."], ["Field Today", "Capture field work, including offline capture on Pro."]] },
            { n: "03", title: "Control & close out", text: "Keep project oversight and commercial records close to the work they describe.", name: "project-dashboard", label: "Project overview", points: [["Project health", "Start with the decisions and exceptions needing attention."], ["Commercial controls", "Manage pay applications and backcharges on Pro."], ["Project records", "Keep drawings, submittals, and RFIs in a shared project workspace."]] },
        ].map(p => <article className="pillar" key={p.n}><div><span className="screen-number">{p.n}</span><h3>{p.title}</h3><p>{p.text}</p><ul>{p.points.map(([title, text]) => <li key={title}><strong>{title}</strong><span>{text}</span></li>)}</ul></div><Capture name={p.name} label={p.label}/></article>)}<Ctas onStart={onStart}/></div></section>
    <section className="workflow-section section-wrap" id="workflow"><div className="section-heading"><div><p className="eyebrow">HOW TO GET STARTED</p><h2>Start with one project.<br />Build from there.</h2></div><p>A free workspace gives you room to start with real work before expanding across your operation.</p></div><div className="onboarding-grid">{[["01", "Create your workspace", "Start with one project and invite a second member.", "project-dashboard", "Project dashboard"], ["02", "Bring the drawings in", "Use Tekla EPM or drawing-log imports, then organize the project record.", "drawing-control", "Drawing control"], ["03", "Work from the same record", "Follow questions, approvals, and readiness with your team.", "rfi-control", "RFIs and actions"]].map(([n, title, text, name, label]) => <article key={n}><div className="onboarding-image"><img src={`/marketing/product/${name}.png`} alt={`Actual ${label} screen`} loading="lazy"/></div><span className="step-number">{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div><Ctas onStart={onStart}/></section>
    <section className="solutions-section section-wrap" id="solutions"><div className="section-heading"><div><p className="eyebrow">BUILT AROUND YOUR ROLE</p><h2>Different responsibilities.<br />The same project reality.</h2></div><p>Keep the information useful to the people responsible for the next handoff.</p></div><div className="role-selector" aria-label="Choose your role">{roles.map((r, i) => <button type="button" key={r.name} aria-pressed={role === i} aria-controls="role-content" onClick={() => setRole(i)}>{r.name}</button>)}</div><div className="role-content" id="role-content"><div><h3>{activeRole.title}</h3><p>{activeRole.pain}</p><p>{activeRole.workflow}</p><div className="role-track">{activeRole.track}</div><Ctas onStart={onStart}/></div><Capture name={activeRole.screen} label={activeRole.name}/></div></section>
    <section className="story-section" id="why-steelbuild"><div className="story-photo"><img src="/marketing/photos/ironworkers-lunch.png" alt="Historical photograph of ironworkers seated on a steel beam above the city" loading="lazy"/><span>THE PEOPLE BEHIND THE STEEL.</span></div><div className="story-copy"><p className="eyebrow">BUILT FROM THE FIELD</p><h2>Built for people<br />who build.</h2><p>Behind every structure are people who detail, fabricate, coordinate, and erect it. People who know one missing answer can hold up an entire crew.</p><p>SteelBuild-Pro brings more than 14 years of ironwork and project management experience to the decisions your team makes every day.</p><Ctas onStart={onStart}/></div></section>
    <section className="pricing-section" id="pricing"><div className="pricing-heading"><div><p className="section-kicker">STRAIGHTFORWARD WORKSPACE PRICING</p><h2>Start lean.<br />Scale when the team is ready.</h2></div><div className="pricing-summary"><p>Create a workspace free in minutes. Upgrade to Pro or Business from Billing when you are ready to roll it out across projects.</p><span>Per workspace, not per user.</span></div></div><div className="pricing-grid">{plans.map((p, i) => <article className={`price-card ${i === 1 ? "price-card-featured" : ""}`} key={p.name}>{i === 1 && <div className="popular-label">MOST POPULAR</div>}<div className="price-card-head"><span>0{i + 1}</span><b>{p.name.toUpperCase()}</b></div><h3>{p.name}</h3><div className="price"><strong>{p.price}</strong>{i > 0 && <span>/ workspace<br />per month</span>}</div><p className="plan-copy">{p.copy}</p><ul>{p.features.map(f => <li key={f}>{f}</li>)}</ul><button type="button" className="price-button" onClick={onStart}>Start free <span>↗︎</span></button></article>)}</div><div className="comparison"><details><summary>Compare plans <span aria-hidden="true">+</span></summary><div className="table-scroll"><table><thead><tr><th>Included</th><th>Free</th><th>Pro</th><th>Business</th></tr></thead><tbody>{[["Projects", "1", "Up to 10", "Unlimited"], ["Members", "2", "Up to 15", "Unlimited"], ["Drawings, submittals & RFIs", "Included", "Included", "Included"], ["Tekla EPM / drawing-log imports", "Included", "Included", "Included"], ["Fab release + production status", "—", "Included", "Included"], ["Pay apps, backcharges & deliveries", "—", "Included", "Included"], ["Field Today + offline capture", "—", "Included", "Included"], ["All modules + priority support", "—", "—", "Included"]].map(([label, ...cells]) => <tr key={label}><th scope="row">{label}</th>{cells.map((c, i) => <td key={i}>{c}</td>)}</tr>)}</tbody></table></div></details></div><Ctas onStart={onStart}/></section>
    <section className="faq-section section-wrap" id="faq"><div><p className="eyebrow">BEFORE YOU GET STARTED</p><h2>Good questions.<br />Straight answers.</h2><Ctas onStart={onStart}/></div><div className="faq-list">{questions.map(([q, a]) => <details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>
    <section className="cta-section" id="contact"><div><p className="eyebrow">YOUR NEXT PROJECT STARTS HERE.</p><h2>Your next steel project.<br /><em>One connected system.</em></h2><p>Start free with one project and two members. No time limit.</p><Ctas onStart={onStart}/></div><div className="cta-brand"><Logo /><p>Built for people who build.</p></div></section>
    <footer className="footer-main"><div className="footer-brand"><Logo /><strong>Built for people who build.</strong><p>Project controls for steel construction.<br />Built for GCs, subcontractors, fabricators, erectors, and owners.</p></div><div className="footer-column"><h3>Product</h3><a href="#platform">Platform</a><a href="#solutions">Solutions</a><a href="#pricing">Pricing</a><button type="button" className="sign-in" onClick={onLogin}>Log in</button></div><div className="footer-column"><h3>Company</h3><a href="#why-steelbuild">Our story</a><a href={demo}>Book a demo</a><a href="mailto:n.lortz1987@gmail.com">Contact</a></div><div className="footer-column"><h3>Resources</h3><a href="#workflow">Getting started</a><a href="#faq">FAQ</a><a href="/Security">Security</a></div><div className="footer-bottom"><span>© 2026 SteelBuild-Pro</span><a href="/Privacy">Privacy</a><a href="/Terms">Terms</a><a href="/Subprocessors">Subprocessors</a><a href="#top">steelbuild-pro.com ↑</a></div></footer>
    </main>;
}
