/**
 * Seed data for Gantt chart
 * Three realistic structural steel projects
 */

const today = new Date();
const getDate = (daysFromToday) => {
  const d = new Date(today);
  d.setDate(d.getDate() + daysFromToday);
  return d;
};

export const GANTT_SEED_DATA = [
  // ═════════════════════════════════════════
  // MESA DISTRIBUTION CENTER
  // ═════════════════════════════════════════

  {
    id: "mesa-group",
    name: "Mesa Distribution Center",
    type: "TASK",
    isGroup: true,
    phase: null,
    startDate: getDate(0),
    endDate: getDate(120),
    parentId: null,
    dependencies: [],
    status: "IN_PROGRESS",
    percentComplete: 35,
    duration: 120,
    assignedCrew: "",
    notes: "",
  },

  // Detailing Phase
  {
    id: "mesa-phase-detail",
    name: "Detailing",
    type: "TASK",
    isGroup: true,
    phase: "Detailing",
    startDate: getDate(0),
    endDate: getDate(20),
    parentId: "mesa-group",
    dependencies: [],
    status: "COMPLETE",
    percentComplete: 100,
    duration: 20,
    assignedCrew: "",
    notes: "",
  },

  {
    id: "mesa-d1",
    name: "Foundation drawings — IFC release",
    type: "TASK",
    isGroup: false,
    phase: "Detailing",
    startDate: getDate(0),
    endDate: getDate(8),
    parentId: "mesa-phase-detail",
    dependencies: [],
    status: "COMPLETE",
    percentComplete: 100,
    duration: 8,
    assignedCrew: "Eng Team",
    notes: "IFC 2x3 format",
  },

  {
    id: "mesa-d2",
    name: "Superstructure IFC drawings",
    type: "TASK",
    isGroup: false,
    phase: "Detailing",
    startDate: getDate(5),
    endDate: getDate(15),
    parentId: "mesa-phase-detail",
    dependencies: ["mesa-d1"],
    status: "COMPLETE",
    percentComplete: 100,
    duration: 10,
    assignedCrew: "Eng Team",
    notes: "",
  },

  {
    id: "mesa-d3",
    name: "Connection details — IFC",
    type: "TASK",
    isGroup: false,
    phase: "Detailing",
    startDate: getDate(12),
    endDate: getDate(20),
    parentId: "mesa-phase-detail",
    dependencies: ["mesa-d2"],
    status: "COMPLETE",
    percentComplete: 100,
    duration: 8,
    assignedCrew: "Eng Team",
    notes: "",
  },

  {
    id: "mesa-m1",
    name: "IFC Drawing Package Complete",
    type: "MILESTONE",
    isGroup: false,
    phase: "Detailing",
    startDate: getDate(21),
    endDate: getDate(21),
    parentId: "mesa-phase-detail",
    dependencies: ["mesa-d3"],
    status: "COMPLETE",
    percentComplete: 100,
    duration: 1,
    assignedCrew: "",
    notes: "",
  },

  // Fabrication Phase
  {
    id: "mesa-phase-fab",
    name: "Fabrication",
    type: "TASK",
    isGroup: true,
    phase: "Fabrication",
    startDate: getDate(22),
    endDate: getDate(65),
    parentId: "mesa-group",
    dependencies: ["mesa-m1"],
    status: "IN_PROGRESS",
    percentComplete: 45,
    duration: 43,
    assignedCrew: "",
    notes: "",
  },

  {
    id: "mesa-f1",
    name: "WP-01 Foundations & Columns",
    type: "TASK",
    isGroup: false,
    phase: "Fabrication",
    startDate: getDate(22),
    endDate: getDate(35),
    parentId: "mesa-phase-fab",
    dependencies: ["mesa-m1"],
    status: "IN_PROGRESS",
    percentComplete: 60,
    duration: 13,
    assignedCrew: "Fab A",
    notes: "",
  },

  {
    id: "mesa-f2",
    name: "WP-02 Main Girders Level 1",
    type: "TASK",
    isGroup: false,
    phase: "Fabrication",
    startDate: getDate(32),
    endDate: getDate(48),
    parentId: "mesa-phase-fab",
    dependencies: ["mesa-f1"],
    status: "IN_PROGRESS",
    percentComplete: 35,
    duration: 16,
    assignedCrew: "Fab B",
    notes: "",
  },

  {
    id: "mesa-f3",
    name: "WP-03 Roof Beams & Joists",
    type: "TASK",
    isGroup: false,
    phase: "Fabrication",
    startDate: getDate(42),
    endDate: getDate(65),
    parentId: "mesa-phase-fab",
    dependencies: ["mesa-f2"],
    status: "NOT_STARTED",
    percentComplete: 0,
    duration: 23,
    assignedCrew: "Fab C",
    notes: "",
  },

  {
    id: "mesa-m2",
    name: "Fabrication Complete",
    type: "MILESTONE",
    isGroup: false,
    phase: "Fabrication",
    startDate: getDate(66),
    endDate: getDate(66),
    parentId: "mesa-phase-fab",
    dependencies: ["mesa-f3"],
    status: "NOT_STARTED",
    percentComplete: 0,
    duration: 1,
    assignedCrew: "",
    notes: "",
  },

  // Delivery Phase
  {
    id: "mesa-phase-deliv",
    name: "Delivery",
    type: "TASK",
    isGroup: true,
    phase: "Delivery",
    startDate: getDate(50),
    endDate: getDate(75),
    parentId: "mesa-group",
    dependencies: [],
    status: "NOT_STARTED",
    percentComplete: 0,
    duration: 25,
    assignedCrew: "",
    notes: "",
  },

  {
    id: "mesa-del1",
    name: "Phase 1 Steel Delivery — Mesa",
    type: "TASK",
    isGroup: false,
    phase: "Delivery",
    startDate: getDate(50),
    endDate: getDate(60),
    parentId: "mesa-phase-deliv",
    dependencies: ["mesa-f1"],
    status: "NOT_STARTED",
    percentComplete: 0,
    duration: 10,
    assignedCrew: "Logistics",
    notes: "",
  },

  {
    id: "mesa-del2",
    name: "Phase 2 Steel Delivery — Mesa",
    type: "TASK",
    isGroup: false,
    phase: "Delivery",
    startDate: getDate(62),
    endDate: getDate(75),
    parentId: "mesa-phase-deliv",
    dependencies: ["mesa-f3"],
    status: "NOT_STARTED",
    percentComplete: 0,
    duration: 13,
    assignedCrew: "Logistics",
    notes: "",
  },

  // Erection Phase
  {
    id: "mesa-phase-erect",
    name: "Erection",
    type: "TASK",
    isGroup: true,
    phase: "Erection",
    startDate: getDate(76),
    endDate: getDate(120),
    parentId: "mesa-group",
    dependencies: ["mesa-m2", "mesa-del2"],
    status: "NOT_STARTED",
    percentComplete: 0,
    duration: 44,
    assignedCrew: "",
    notes: "",
  },

  {
    id: "mesa-e1",
    name: "Erection — Grid A Columns",
    type: "TASK",
    isGroup: false,
    phase: "Erection",
    startDate: getDate(76),
    endDate: getDate(88),
    parentId: "mesa-phase-erect",
    dependencies: ["mesa-m2"],
    status: "NOT_STARTED",
    percentComplete: 0,
    duration: 12,
    assignedCrew: "Erect Crew",
    notes: "",
  },

  {
    id: "mesa-e2",
    name: "Erection — Grid B Columns",
    type: "TASK",
    isGroup: false,
    phase: "Erection",
    startDate: getDate(89),
    endDate: getDate(100),
    parentId: "mesa-phase-erect",
    dependencies: ["mesa-e1"],
    status: "NOT_STARTED",
    percentComplete: 0,
    duration: 11,
    assignedCrew: "Erect Crew",
    notes: "Depends on Grid A completion",
  },

  {
    id: "mesa-e3",
    name: "Main Roof Framing",
    type: "TASK",
    isGroup: false,
    phase: "Erection",
    startDate: getDate(101),
    endDate: getDate(112),
    parentId: "mesa-phase-erect",
    dependencies: ["mesa-e2"],
    status: "NOT_STARTED",
    percentComplete: 0,
    duration: 11,
    assignedCrew: "Erect Crew",
    notes: "",
  },

  {
    id: "mesa-e4",
    name: "Decking & Misc",
    type: "TASK",
    isGroup: false,
    phase: "Erection",
    startDate: getDate(110),
    endDate: getDate(120),
    parentId: "mesa-phase-erect",
    dependencies: ["mesa-e3"],
    status: "NOT_STARTED",
    percentComplete: 0,
    duration: 10,
    assignedCrew: "Misc Crew",
    notes: "",
  },

  {
    id: "mesa-m3",
    name: "Steel Erection Complete",
    type: "MILESTONE",
    isGroup: false,
    phase: "Erection",
    startDate: getDate(121),
    endDate: getDate(121),
    parentId: "mesa-phase-erect",
    dependencies: ["mesa-e4"],
    status: "NOT_STARTED",
    percentComplete: 0,
    duration: 1,
    assignedCrew: "",
    notes: "",
  },

  // ═════════════════════════════════════════
  // RIVERSIDE WAREHOUSE
  // ═════════════════════════════════════════

  {
    id: "river-group",
    name: "Riverside Warehouse",
    type: "TASK",
    isGroup: true,
    phase: null,
    startDate: getDate(10),
    endDate: getDate(95),
    parentId: null,
    dependencies: [],
    status: "IN_PROGRESS",
    percentComplete: 55,
    duration: 85,
    assignedCrew: "",
    notes: "",
  },

  {
    id: "river-phase-detail",
    name: "Detailing",
    type: "TASK",
    isGroup: true,
    phase: "Detailing",
    startDate: getDate(10),
    endDate: getDate(25),
    parentId: "river-group",
    dependencies: [],
    status: "COMPLETE",
    percentComplete: 100,
    duration: 15,
    assignedCrew: "",
    notes: "",
  },

  {
    id: "river-d1",
    name: "Foundation & Framing IFC",
    type: "TASK",
    isGroup: false,
    phase: "Detailing",
    startDate: getDate(10),
    endDate: getDate(20),
    parentId: "river-phase-detail",
    dependencies: [],
    status: "COMPLETE",
    percentComplete: 100,
    duration: 10,
    assignedCrew: "Design",
    notes: "",
  },

  {
    id: "river-d2",
    name: "Miscellaneous connections",
    type: "TASK",
    isGroup: false,
    phase: "Detailing",
    startDate: getDate(18),
    endDate: getDate(25),
    parentId: "river-phase-detail",
    dependencies: ["river-d1"],
    status: "COMPLETE",
    percentComplete: 100,
    duration: 7,
    assignedCrew: "Design",
    notes: "",
  },

  {
    id: "river-m1",
    name: "Detailing Approved",
    type: "MILESTONE",
    isGroup: false,
    phase: "Detailing",
    startDate: getDate(26),
    endDate: getDate(26),
    parentId: "river-phase-detail",
    dependencies: ["river-d2"],
    status: "COMPLETE",
    percentComplete: 100,
    duration: 1,
    assignedCrew: "",
    notes: "",
  },

  {
    id: "river-phase-fab",
    name: "Fabrication",
    type: "TASK",
    isGroup: true,
    phase: "Fabrication",
    startDate: getDate(27),
    endDate: getDate(65),
    parentId: "river-group",
    dependencies: ["river-m1"],
    status: "IN_PROGRESS",
    percentComplete: 70,
    duration: 38,
    assignedCrew: "",
    notes: "",
  },

  {
    id: "river-f1",
    name: "WP-04 Columns & Bases",
    type: "TASK",
    isGroup: false,
    phase: "Fabrication",
    startDate: getDate(27),
    endDate: getDate(40),
    parentId: "river-phase-fab",
    dependencies: ["river-m1"],
    status: "COMPLETE",
    percentComplete: 100,
    duration: 13,
    assignedCrew: "Fab A",
    notes: "",
  },

  {
    id: "river-f2",
    name: "WP-05 Primary Beams",
    type: "TASK",
    isGroup: false,
    phase: "Fabrication",
    startDate: getDate(38),
    endDate: getDate(55),
    parentId: "river-phase-fab",
    dependencies: ["river-f1"],
    status: "IN_PROGRESS",
    percentComplete: 80,
    duration: 17,
    assignedCrew: "Fab B",
    notes: "",
  },

  {
    id: "river-f3",
    name: "WP-06 Deck & Misc",
    type: "TASK",
    isGroup: false,
    phase: "Fabrication",
    startDate: getDate(52),
    endDate: getDate(65),
    parentId: "river-phase-fab",
    dependencies: ["river-f2"],
    status: "NOT_STARTED",
    percentComplete: 0,
    duration: 13,
    assignedCrew: "Fab C",
    notes: "",
  },

  {
    id: "river-phase-erect",
    name: "Erection",
    type: "TASK",
    isGroup: true,
    phase: "Erection",
    startDate: getDate(66),
    endDate: getDate(95),
    parentId: "river-group",
    dependencies: ["river-f3"],
    status: "NOT_STARTED",
    percentComplete: 0,
    duration: 29,
    assignedCrew: "",
    notes: "",
  },

  {
    id: "river-e1",
    name: "Structural Frame Erection",
    type: "TASK",
    isGroup: false,
    phase: "Erection",
    startDate: getDate(66),
    endDate: getDate(82),
    parentId: "river-phase-erect",
    dependencies: ["river-f3"],
    status: "NOT_STARTED",
    percentComplete: 0,
    duration: 16,
    assignedCrew: "Erect A",
    notes: "",
  },

  {
    id: "river-e2",
    name: "Roof & Decking Installation",
    type: "TASK",
    isGroup: false,
    phase: "Erection",
    startDate: getDate(80),
    endDate: getDate(95),
    parentId: "river-phase-erect",
    dependencies: ["river-e1"],
    status: "NOT_STARTED",
    percentComplete: 0,
    duration: 15,
    assignedCrew: "Erect B",
    notes: "",
  },

  // ═════════════════════════════════════════
  // CHANDLER OFFICE BUILD
  // ═════════════════════════════════════════

  {
    id: "chandler-group",
    name: "Chandler Office Build",
    type: "TASK",
    isGroup: true,
    phase: null,
    startDate: getDate(-45),
    endDate: getDate(30),
    parentId: null,
    dependencies: [],
    status: "IN_PROGRESS",
    percentComplete: 82,
    duration: 75,
    assignedCrew: "",
    notes: "",
  },

  {
    id: "chandler-phase-fab",
    name: "Fabrication",
    type: "TASK",
    isGroup: true,
    phase: "Fabrication",
    startDate: getDate(-45),
    endDate: getDate(-8),
    parentId: "chandler-group",
    dependencies: [],
    status: "COMPLETE",
    percentComplete: 100,
    duration: 37,
    assignedCrew: "",
    notes: "",
  },

  {
    id: "chandler-f1",
    name: "WP-07 Steel Frame",
    type: "TASK",
    isGroup: false,
    phase: "Fabrication",
    startDate: getDate(-45),
    endDate: getDate(-28),
    parentId: "chandler-phase-fab",
    dependencies: [],
    status: "COMPLETE",
    percentComplete: 100,
    duration: 17,
    assignedCrew: "Fab A",
    notes: "",
  },

  {
    id: "chandler-f2",
    name: "WP-08 Misc Connections",
    type: "TASK",
    isGroup: false,
    phase: "Fabrication",
    startDate: getDate(-25),
    endDate: getDate(-8),
    parentId: "chandler-phase-fab",
    dependencies: ["chandler-f1"],
    status: "COMPLETE",
    percentComplete: 100,
    duration: 17,
    assignedCrew: "Fab B",
    notes: "",
  },

  {
    id: "chandler-phase-erect",
    name: "Erection",
    type: "TASK",
    isGroup: true,
    phase: "Erection",
    startDate: getDate(-7),
    endDate: getDate(30),
    parentId: "chandler-group",
    dependencies: ["chandler-f2"],
    status: "IN_PROGRESS",
    percentComplete: 75,
    duration: 37,
    assignedCrew: "",
    notes: "",
  },

  {
    id: "chandler-e1",
    name: "Structural Steel Installation",
    type: "TASK",
    isGroup: false,
    phase: "Erection",
    startDate: getDate(-7),
    endDate: getDate(12),
    parentId: "chandler-phase-erect",
    dependencies: ["chandler-f2"],
    status: "IN_PROGRESS",
    percentComplete: 85,
    duration: 19,
    assignedCrew: "Erect A",
    notes: "",
  },

  {
    id: "chandler-e2",
    name: "Decking & Finishing",
    type: "TASK",
    isGroup: false,
    phase: "Erection",
    startDate: getDate(8),
    endDate: getDate(30),
    parentId: "chandler-phase-erect",
    dependencies: ["chandler-e1"],
    status: "IN_PROGRESS",
    percentComplete: 65,
    duration: 22,
    assignedCrew: "Erect B",
    notes: "",
  },

  {
    id: "chandler-m1",
    name: "Project Complete",
    type: "MILESTONE",
    isGroup: false,
    phase: "Erection",
    startDate: getDate(31),
    endDate: getDate(31),
    parentId: "chandler-phase-erect",
    dependencies: ["chandler-e2"],
    status: "NOT_STARTED",
    percentComplete: 0,
    duration: 1,
    assignedCrew: "",
    notes: "",
  },
];