/**
 * payAppPdf.js — the AIA-style pay application as a PDF: page 1 is the G702
 * (Application & Certificate for Payment, the 9-line summary), the rest is the
 * G703 continuation sheet (the SOV line table, landscape). Client-side via
 * jsPDF (manual layout). All figures come from the G702 engine so the PDF
 * reconciles to the on-screen totals to the penny.
 */
import { jsPDF } from "jspdf";
import { formatLocalDate } from "@/utils/dates";
import { formatMoney, sumMoney } from "@/lib/money";
import { computeG702, lineFigures } from "./g702";

const C = { black: [15, 17, 24], accent: [0, 120, 150], muted: [100, 110, 130], border: [200, 206, 216], rowEven: [245, 247, 250], white: [255, 255, 255] };
const m = (v) => formatMoney(v);
const num = (v) => (Number.isFinite(Number(v)) ? Number(v) : 0);

export function buildPayAppPdf({ app, lines = [], project = {} } = {}) {
  const contract = { originalContractSum: num(app?.original_contract_sum), netChangeOrders: num(app?.net_change_orders), retainagePercent: num(app?.retainage_percent) };
  const g = computeG702({ contract, lines, lessPreviousCertificates: num(app?.less_previous_certificates) });
  const pdf = new jsPDF({ orientation: "portrait", unit: "pt", format: "letter" });
  const font = (s, w = "normal") => { pdf.setFontSize(s); pdf.setFont("helvetica", w === "bold" ? "bold" : "normal"); };
  const color = (c) => pdf.setTextColor(...c);
  const fill = (c) => pdf.setFillColor(...c);
  const draw = (c) => pdf.setDrawColor(...c);

  // ════ Page 1 — G702 ════════════════════════════════════════════════════════
  const PW = 612, M = 48;
  fill(C.black); pdf.rect(0, 0, PW, 58, "F");
  color(C.white); font(15, "bold"); pdf.text("APPLICATION AND CERTIFICATE FOR PAYMENT", M, 30);
  color([180, 190, 205]); font(8); pdf.text("AIA Document G702 — generated by SteelBuild Pro", M, 46);
  let y = 80;

  const kv = (k, v, x, w) => { font(7, "bold"); color(C.muted); pdf.text(String(k).toUpperCase(), x, y); font(10); color(C.black); pdf.text(String(v ?? "—"), x, y + 13); };
  kv("Project", project?.name || project?.project_number || "—", M, 260);
  kv("To (Owner / GC)", project?.general_contractor || "—", M + 280, 240);
  y += 34;
  kv("Application No.", String(app?.application_number ?? "—"), M, 120);
  kv("Period", `${app?.period_from ? formatLocalDate(app.period_from) : "—"} – ${app?.period_to ? formatLocalDate(app.period_to) : "—"}`, M + 140, 200);
  kv("Application Date", app?.submitted_date ? formatLocalDate(app.submitted_date) : formatLocalDate(app?.created_at), M + 360, 150);
  y += 40;

  // The 9 G702 lines
  const lineRow = (no, label, value, opts = {}) => {
    if (opts.fill) { fill(opts.fill); pdf.rect(M, y - 11, PW - M * 2, 18, "F"); }
    font(9, opts.bold ? "bold" : "normal"); color(C.muted); pdf.text(String(no), M + 4, y);
    color(C.black); pdf.text(label, M + 28, y);
    font(opts.bold ? 11 : 10, opts.bold ? "bold" : "normal"); color(opts.tone || C.black);
    pdf.text(m(value), PW - M - 6, y, { align: "right" });
    y += 18;
  };
  draw(C.border); pdf.setLineWidth(0.5);
  lineRow("1", "Original Contract Sum", g.originalContractSum);
  lineRow("2", "Net change by Change Orders", g.netChangeOrders);
  lineRow("3", "Contract Sum to Date (1 + 2)", g.contractSumToDate, { bold: true, fill: C.rowEven });
  lineRow("4", "Total Completed & Stored to Date", g.totalCompletedStored);
  lineRow("5", "Retainage", g.totalRetainage);
  lineRow("6", "Total Earned Less Retainage (4 − 5)", g.totalEarnedLessRetainage, { bold: true, fill: C.rowEven });
  lineRow("7", "Less Previous Certificates for Payment", g.lessPreviousCertificates);
  lineRow("8", "CURRENT PAYMENT DUE (6 − 7)", g.currentPaymentDue, { bold: true, tone: C.accent, fill: [235, 245, 248] });
  lineRow("9", "Balance to Finish, Incl. Retainage (3 − 6)", g.balanceToFinish);
  y += 24;

  // Certification + signature
  font(8); color(C.muted);
  const cert = pdf.splitTextToSize("The undersigned Contractor certifies that to the best of the Contractor's knowledge, information and belief the Work covered by this Application for Payment has been completed in accordance with the Contract Documents, that all amounts have been paid by the Contractor for Work for which previous Certificates for Payment were issued and payments received from the Owner, and that current payment shown herein is now due.", PW - M * 2);
  pdf.text(cert, M, y); y += cert.length * 11 + 30;
  draw(C.muted); pdf.line(M, y, M + 220, y); pdf.line(PW - M - 160, y, PW - M, y);
  font(8); color(C.muted);
  pdf.text("Contractor — signature & date", M, y + 12);
  pdf.text("Application date", PW - M - 160, y + 12);

  // ════ G703 continuation sheet (landscape) ═══════════════════════════════════
  pdf.addPage("letter", "landscape");
  const LW = 792, LM = 36;
  fill(C.black); pdf.rect(0, 0, LW, 40, "F");
  color(C.white); font(12, "bold"); pdf.text("CONTINUATION SHEET (AIA G703)", LM, 26);
  color([180, 190, 205]); font(8); pdf.text(`Application No. ${app?.application_number ?? "—"} — ${project?.name || ""}`, LW - LM, 26, { align: "right" });
  let ly = 64;

  const cols = [
    { k: "a", w: 30, label: "Item" },
    { k: "b", w: 150, label: "Description of Work" },
    { k: "c", w: 72, label: "Scheduled Value", align: "right" },
    { k: "d", w: 68, label: "From Previous", align: "right" },
    { k: "e", w: 68, label: "This Period", align: "right" },
    { k: "f", w: 64, label: "Stored Matl", align: "right" },
    { k: "g", w: 78, label: "Total Compl+Stored", align: "right" },
    { k: "pct", w: 40, label: "%", align: "right" },
    { k: "h", w: 72, label: "Balance to Finish", align: "right" },
    { k: "i", w: 64, label: "Retainage", align: "right" },
  ];
  const drawCells = (cells, opts = {}) => {
    if (ly > 560) { pdf.addPage("letter", "landscape"); ly = 48; }
    if (opts.fill) { fill(opts.fill); pdf.rect(LM, ly - 10, LW - LM * 2, 15, "F"); }
    font(opts.head ? 7 : 7.5, opts.bold || opts.head ? "bold" : "normal");
    color(opts.head ? C.white : C.black);
    let x = LM;
    for (const c of cols) {
      const txt = String(cells[c.k] ?? "");
      const tx = c.align === "right" ? x + c.w - 3 : x + 3;
      pdf.text(pdf.splitTextToSize(txt, c.w - 5)[0] || "", tx, ly, { align: c.align || "left" });
      x += c.w;
    }
    ly += 15;
  };
  fill(C.black); pdf.rect(LM, ly - 10, LW - LM * 2, 15, "F");
  drawCells(Object.fromEntries(cols.map((c) => [c.k, c.label])), { head: true });

  (lines || []).forEach((l, i) => {
    const f = lineFigures(l);
    drawCells({
      a: l.line_item_number || String(i + 1),
      b: l.description || "",
      c: m(l.scheduled_value),
      d: m(l.work_completed_previous),
      e: m(l.work_completed_this_period),
      f: m(l.materials_stored),
      g: m(f.totalCompletedStored),
      pct: `${num(f.displayPercent)}%`,
      h: m(f.balanceToFinish),
      i: m(l.retainage),
    }, { fill: i % 2 === 1 ? C.rowEven : null });
  });
  drawCells({
    a: "", b: "GRAND TOTAL",
    c: m(sumMoney((lines || []).map((l) => l.scheduled_value))),
    d: m(sumMoney((lines || []).map((l) => l.work_completed_previous))),
    e: m(sumMoney((lines || []).map((l) => l.work_completed_this_period))),
    f: m(sumMoney((lines || []).map((l) => l.materials_stored))),
    g: m(g.totalCompletedStored), pct: "",
    h: m(sumMoney((lines || []).map((l) => lineFigures(l).balanceToFinish))),
    i: m(g.totalRetainage),
  }, { bold: true, fill: [230, 236, 244] });

  // Footers
  const pages = pdf.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    pdf.setPage(p);
    const w = pdf.internal.pageSize.getWidth();
    font(7); color(C.muted);
    pdf.text(`Pay Application ${app?.application_number ?? ""} — ${project?.name || ""}`, 40, pdf.internal.pageSize.getHeight() - 20);
    pdf.text(`Page ${p} of ${pages}`, w - 40, pdf.internal.pageSize.getHeight() - 20, { align: "right" });
  }
  return pdf;
}

/** Filename stem for the pay-app PDF. */
export function suggestPayAppFilename(app, project) {
  const job = String(project?.project_number || "").replace(/[^A-Za-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
  return [job, "PayApp", String(app?.application_number ?? "")].filter(Boolean).join("_") || "PayApp";
}
