-- Account deletion (App Store guideline 5.1.1(v)): stop authorship references
-- from blocking auth.users deletes, and erase a user's sole-member workspaces
-- in one transaction.
--
-- 27 foreign keys to auth.users have no ON DELETE rule (NO ACTION), so the
-- account-delete Edge Function's auth.admin.deleteUser fails with "Database
-- error deleting user" for anyone who ever created one of those rows in a
-- workspace that outlives their account.
--
-- 1. 16 plain authorship columns (created / reviewed / sent / locked /
--    invited / generated by): ON DELETE SET NULL. The record stays and just
--    loses the link to the deleted user. All 16 are nullable.
-- 2. 11 audit and sign-off columns (fab releases, release overrides, drawing
--    sign-off stamps and voids, backcharge events, material receipts and
--    receipt verification, piece-import upload / approval / apply): the
--    foreign key is dropped and the uuid kept, so the trail still records
--    who did it after their login is deleted (owner decision, 2026-09-27).
--    Two of these columns are NOT NULL and could not be cleared anyway.
-- 3. public.erase_my_sole_member_workspaces(p_reason): archive, then erase,
--    every workspace where the caller is the only member and owner, all in
--    one transaction, returning the erased org and project ids for the
--    Edge Function's Storage purge.
--
-- Constraints are found in the catalog by (table, column) rather than by
-- name, so a differently named constraint in production is still replaced,
-- and the migration aborts if any targeted column still blocks deletion.

do $$
declare
  r record;
  v_rel regclass;
  v_names text[];
  v_name text;
  v_keep_name text;
begin
  for r in
    select * from (values
      -- 1. SET NULL: plain authorship.
      ('backcharge_tm_tickets',       'created_by',          'set_null'),
      ('backcharges',                 'created_by',          'set_null'),
      ('comments',                    'status_changed_by',   'set_null'),
      ('drawing_revision_summaries',  'generated_by',        'set_null'),
      ('drawing_sets',                'locked_by',           'set_null'),
      ('email_accounts',              'created_by',          'set_null'),
      ('email_intake_queue',          'reviewed_by',         'set_null'),
      ('email_messages',              'reviewed_by',         'set_null'),
      ('email_messages',              'sent_by',             'set_null'),
      ('organization_invitations',    'invited_by',          'set_null'),
      ('organizations',               'created_by',          'set_null'),
      ('pay_applications',            'created_by',          'set_null'),
      ('piece_drawings',              'created_by',          'set_null'),
      ('material_requirements',       'created_by',          'set_null'),
      ('piece_material_requirements', 'created_by',          'set_null'),
      ('piece_drawing_sets',          'created_by',          'set_null'),
      -- 2. Keep the uuid, drop the foreign key: audit and sign-off records.
      ('backcharge_events',           'actor',               'keep_id'),
      ('drawing_signoffs',            'stamped_by_id',       'keep_id'),
      ('drawing_signoffs',            'voided_by',           'keep_id'),
      ('fab_release_log',             'released_by',         'keep_id'),
      ('fab_release_overrides',       'overridden_by',       'keep_id'),
      ('fab_releases',                'released_by',         'keep_id'),
      ('material_receipt_events',     'recorded_by',         'keep_id'),
      ('material_requirements',       'receipt_verified_by', 'keep_id'),
      ('piece_import_batches',        'uploaded_by',         'keep_id'),
      ('piece_import_batches',        'approved_by',         'keep_id'),
      ('piece_import_batches',        'applied_by',          'keep_id')
    ) as t(tbl, col, action)
  loop
    v_rel := to_regclass(format('public.%I', r.tbl));
    if v_rel is null then
      raise notice 'account-deletion FKs: table public.% not found, skipped', r.tbl;
      continue;
    end if;

    -- Drop every foreign key from this column to auth.users, then (for
    -- set_null) re-add exactly one under the first dropped name. Names are
    -- collected first so no catalog cursor stays open across the ALTERs.
    select coalesce(array_agg(con.conname::text order by con.conname), '{}')
      into v_names
    from pg_catalog.pg_constraint con
    join pg_catalog.pg_attribute att
      on att.attrelid = con.conrelid and att.attnum = con.conkey[1]
    where con.contype = 'f'
      and con.conrelid = v_rel
      and con.confrelid = 'auth.users'::regclass
      and array_length(con.conkey, 1) = 1
      and att.attname = r.col;

    v_keep_name := v_names[1];
    foreach v_name in array v_names loop
      execute format('alter table public.%I drop constraint %I', r.tbl, v_name);
    end loop;

    if v_keep_name is null then
      raise notice 'account-deletion FKs: no foreign key to auth.users on public.%.%, nothing to change', r.tbl, r.col;
    elsif r.action = 'set_null' then
      execute format(
        'alter table public.%I add constraint %I foreign key (%I) references auth.users (id) on delete set null',
        r.tbl, v_keep_name, r.col
      );
    end if;
  end loop;
end
$$;

-- Abort if any targeted column still blocks an auth.users delete, and report
-- any other NO ACTION / RESTRICT foreign key to auth.users in public (for
-- example from tables created outside this repo) without failing on it.
do $$
declare
  v_blocking text;
  v_other text;
begin
  select string_agg(format('public.%s.%s (%s)', cls.relname, att.attname, con.conname), ', ')
    into v_blocking
  from pg_catalog.pg_constraint con
  join pg_catalog.pg_class cls on cls.oid = con.conrelid
  join pg_catalog.pg_attribute att
    on att.attrelid = con.conrelid and att.attnum = con.conkey[1]
  where con.contype = 'f'
    and con.confrelid = 'auth.users'::regclass
    and con.confdeltype in ('a', 'r')
    and cls.relnamespace = 'public'::regnamespace
    and (cls.relname::text, att.attname::text) in (
      ('backcharge_tm_tickets', 'created_by'), ('backcharges', 'created_by'),
      ('comments', 'status_changed_by'), ('drawing_revision_summaries', 'generated_by'),
      ('drawing_sets', 'locked_by'), ('email_accounts', 'created_by'),
      ('email_intake_queue', 'reviewed_by'), ('email_messages', 'reviewed_by'),
      ('email_messages', 'sent_by'), ('organization_invitations', 'invited_by'),
      ('organizations', 'created_by'), ('pay_applications', 'created_by'),
      ('piece_drawings', 'created_by'), ('material_requirements', 'created_by'),
      ('piece_material_requirements', 'created_by'), ('piece_drawing_sets', 'created_by'),
      ('backcharge_events', 'actor'), ('drawing_signoffs', 'stamped_by_id'),
      ('drawing_signoffs', 'voided_by'), ('fab_release_log', 'released_by'),
      ('fab_release_overrides', 'overridden_by'), ('fab_releases', 'released_by'),
      ('material_receipt_events', 'recorded_by'), ('material_requirements', 'receipt_verified_by'),
      ('piece_import_batches', 'uploaded_by'), ('piece_import_batches', 'approved_by'),
      ('piece_import_batches', 'applied_by')
    );
  if v_blocking is not null then
    raise exception 'account-deletion FKs: still blocking auth.users deletes: %', v_blocking;
  end if;

  select string_agg(format('public.%s.%s (%s)', cls.relname, att.attname, con.conname), ', ')
    into v_other
  from pg_catalog.pg_constraint con
  join pg_catalog.pg_class cls on cls.oid = con.conrelid
  join pg_catalog.pg_attribute att
    on att.attrelid = con.conrelid and att.attnum = con.conkey[1]
  where con.contype = 'f'
    and con.confrelid = 'auth.users'::regclass
    and con.confdeltype in ('a', 'r')
    and cls.relnamespace = 'public'::regnamespace;
  if v_other is not null then
    raise notice 'account-deletion FKs: other foreign keys to auth.users still block deletes: %', v_other;
  end if;
end
$$;

-- 3. One-transaction erase of the caller's sole-member workspaces.
create or replace function public.erase_my_sole_member_workspaces(p_reason text)
returns jsonb
language plpgsql
security definer
set search_path to ''
-- PostgREST 14 hoists this catalog setting before starting the RPC statement,
-- overriding authenticated's 8s timer for this RPC only. SET LOCAL inside the
-- body would be too late. Stay within the API's 60s maximum; do not widen the
-- authenticated role's limit. Reload the schema cache after applying below.
set statement_timeout to '60s'
as $function$
declare
  v_uid uuid := (select auth.uid());
  v_org uuid;
  v_project uuid;
  v_locked_org_ids uuid[];
  v_todo uuid[];
  v_live uuid[];
  v_org_ids uuid[] := '{}';
  v_project_ids uuid[] := '{}';
begin
  if v_uid is null then
    raise exception 'Not signed in' using errcode = '42501';
  end if;

  -- Membership writes lock the parent organization in enforce_org_member_guard.
  -- Take that same lock before deciding an org is sole-member; an invitation
  -- accepted between a stale roster read and erasure must never erase a team.
  -- Materialize the locked ids before trigger-toggling erasure begins below.
  -- A workspace created concurrently is not part of this locked snapshot.
  select coalesce(array_agg(locked.id), '{}') into v_locked_org_ids
  from (
    select o.id from public.organizations o
    where exists (
      select 1 from public.organization_members m
      where m.org_id = o.id and m.user_id = v_uid and m.role = 'owner'
    )
    order by o.id
    for update
  ) locked;

  -- Workspaces where the caller is the only member and an owner. Shared
  -- workspaces are never touched here; the Edge Function refuses deletion
  -- while the caller is the only owner of one.
  --
  -- Ids are collected into arrays before anything is changed: no cursor may
  -- stay open over organization_members or projects while
  -- hard_delete_organization toggles their triggers (error 55006, see
  -- 20260912062606).
  select coalesce(array_agg(m.org_id order by m.org_id), '{}')
    into v_todo
  from public.organization_members m
  where m.user_id = v_uid
    and m.org_id = any(v_locked_org_ids)
    and m.role = 'owner'
    and not exists (
      select 1 from public.organization_members o
      where o.org_id = m.org_id and o.user_id <> v_uid
    );

  foreach v_org in array v_todo loop
    -- hard_delete_organization refuses live projects (ARCHIVE_FIRST).
    select coalesce(array_agg(p.id), '{}')
      into v_live
    from public.projects p
    where p.org_id = v_org and coalesce(p.is_deleted, false) = false;

    foreach v_project in array v_live loop
      perform public.soft_delete_project(v_project);
    end loop;

    v_project_ids := v_project_ids || array(select p.id from public.projects p where p.org_id = v_org);
    -- Re-checks ownership and the reason itself.
    perform public.hard_delete_organization(v_org, p_reason);
    v_org_ids := v_org_ids || v_org;
  end loop;

  return jsonb_build_object('org_ids', to_jsonb(v_org_ids), 'project_ids', to_jsonb(v_project_ids));
end;
$function$;

revoke all on function public.erase_my_sole_member_workspaces(text) from public, anon;
grant execute on function public.erase_my_sole_member_workspaces(text) to authenticated;

-- PostgREST reads the function's timeout from the schema cache before executing
-- it. Direct SQL callers must set their timeout before the SELECT themselves.
notify pgrst, 'reload schema';
