Attribute VB_Name = "mSchema"
'Auto-generated by build_app_shell.py - do not edit by hand
Option Explicit

Public Const SB_URL As String = "https://kjrwqagyeswwoxpjkcko.supabase.co"
Public Const SB_ANON As String = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqcndxYWd5ZXN3d294cGprY2tvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0NjA5OTAsImV4cCI6MjA5MTAzNjk5MH0.2JvQQizgxARmDY-55zlWI18NJ5e1TpHBAKg_0Cw5L58"
Public Const HEADER_ROW As Long = 6

' Returns array of module defs; each = Array(key, table, sheet, projectFiltered, order, colsCsv, typesCsv)
Public Function Modules() As Variant
    Dim m(0 To 8) As Variant
    m(0) = Array("drawing_sets","drawing_sets","Drawing Sets",True,"issued_date.asc","set_name,discipline,revision,status,set_approval_status,is_locked,sheet_count,issued_date,locked_reason","text,text,text,chip:sub_status,chip:set_approval,check,num,date,text")
    m(1) = Array("drawings","drawings","Drawings",True,"sheet_number.asc","sheet_number,title,discipline,revision_number,stage,drawing_set_name,submitted_date,return_date,is_superseded","text,text,text,text,chip:dwg_stage,text,date,date,check")
    m(2) = Array("submittals","submittals","Submittals",True,"submitted_date.asc","submittal_number,title,spec_section,discipline,revision,round_number,status,ball_in_court,reviewer,submitted_date,required_date,returned_date","text,text,text,text,text,num,chip:sub_status,text,text,date,date,date")
    m(3) = Array("rfis","rfis","RFIs",True,"submitted_date.asc","rfi_number,title,discipline,status,priority,ball_in_court,assigned_to,submitted_date,date_answered,cost_impact,schedule_impact,question,answer","text,text,text,chip:rfi_status,chip:priority,text,text,date,date,check,check,wrap,wrap")
    m(4) = Array("schedule_tasks","schedule_tasks","Schedule",True,"start_date.asc","wbs_code,task_name,task_type,phase,status,priority,percent_complete,start_date,end_date,crew_name,is_milestone","text,text,text,text,chip:sched_status,chip:priority,pct,date,date,text,check")
    m(5) = Array("work_packages","work_packages","Work Packages",True,"wp_number.asc","wp_number,name,phase,status,percent_complete,area,crew,released_date,scheduled_start_date,scheduled_end_date","text,text,text,chip:wp_status,pct,text,text,date,date,date")
    m(6) = Array("deliveries","deliveries","Deliveries",True,"scheduled_date.asc","load_number,description,vendor,status,priority,pieces,weight_tons,area,scheduled_date,actual_date","text,text,text,chip:sub_status,chip:priority,num,tons,text,date,date")
    m(7) = Array("change_orders","change_orders","Change Orders",True,"co_number.asc","co_number,title,status,co_amount,reason_code,schedule_impact_days,submitted_date,approved_date,description","text,text,chip:co_status,money,text,num,date,date,wrap")
    m(8) = Array("vendors","vendors","Vendors",False,"company_name.asc","company_name,vendor_type,contact_person,title,phone,email,state,is_preferred,payment_terms,status","text,text,text,text,text,text,text,check,text,chip:sub_status")
    Modules = m
End Function