/** Realistic structural-steel fabrication mock data for SteelBuild Pro prototype */

window.MOCK_PROJECT = {
  id: "25372",
  number: "25372",
  name: "Medina Station Phase II",
  client: "SimonCRE Buddy, LLC",
  gc: "Whiting-Turner",
  contract_type: "Lump Sum",
  current_phase: "Erection",
  status: "On Track",
  start: "Sep 2, 2025",
  target_complete: "Jun 1, 2026",
  forecast: "Jun 1, 2026",
  days_remaining: 43,
  timeline_pct: 84,
  progress_pct: 61,
  contract_value: 756549,
  budget_committed: 756549,
  cost_to_date: 0,
  committed_costs: 15685,
  cost_variance: 756549,
  budget_burn: 0,
  total_tons: 842.5,
  erected_tons: 514.2,
  fab_tons: 198.0,
  wp_progress: 0,
  fab_progress: 68,
  erected_progress: 61,
};

window.MOCK_KPIS = {
  rfis_open: 8,
  rfis_overdue: 2,
  rfis_aging_7: 3,
  rfis_aging_14: 2,
  rfis_aging_30: 3,
  drawings_in_review: 4,
  drawings_overdue: 0,
  drawings_released: 68,
  drawings_total: 75,
  wps_total: 14,
  wps_complete: 0,
  wps_in_progress: 6,
  deliveries_scheduled: 4,
  deliveries_overdue: 0,
  change_orders_pending: 3,
  action_items: 7,
};

window.MOCK_RFIS = [
  {
    "id": "RFI-170",
    "title": "Girt spacing clarification — bay 1",
    "discipline": "Anchor Bolts",
    "status": "Open",
    "bic": "Owner",
    "submitted": "2026-04-28",
    "required": "2026-04-28",
    "age": 1,
    "priority": "Medium",
    "submitter": "S. Reyes",
    "cost_impact": 6900
  },
  {
    "id": "RFI-169",
    "title": "Embed plate layout at loading dock — clarification",
    "discipline": "Decking",
    "status": "Open",
    "bic": "Engineer",
    "submitted": "2026-04-27",
    "required": "2026-04-27",
    "age": 2,
    "priority": "Low",
    "submitter": "M. Ortega",
    "cost_impact": 0
  },
  {
    "id": "RFI-168",
    "title": "Paint system compatibility with existing coating",
    "discipline": "Anchor Bolts",
    "status": "Under Review",
    "bic": "Architect",
    "submitted": "2026-04-26",
    "required": "2026-04-26",
    "age": 3,
    "priority": "Medium",
    "submitter": "A. Chen",
    "cost_impact": 11500
  },
  {
    "id": "RFI-167",
    "title": "Erection sequence bay 10 — N",
    "discipline": "Decking",
    "status": "Open",
    "bic": "Contractor",
    "submitted": "2026-04-25",
    "required": "2026-04-25",
    "age": 4,
    "priority": "Medium",
    "submitter": "S. Reyes",
    "cost_impact": 0
  },
  {
    "id": "RFI-166",
    "title": "Beam W8x76 connection at SE corner — GL E/1",
    "discipline": "Anchor Bolts",
    "status": "Under Review",
    "bic": "Owner",
    "submitted": "2026-04-24",
    "required": "2026-04-24",
    "age": 5,
    "priority": "Medium",
    "submitter": "J. Patel",
    "cost_impact": 0
  },
  {
    "id": "RFI-165",
    "title": "Shear tab thickness on GL H/10",
    "discipline": "Decking",
    "status": "Open",
    "bic": "Contractor",
    "submitted": "2026-04-23",
    "required": "2026-04-23",
    "age": 6,
    "priority": "Critical",
    "submitter": "K. Nguyen",
    "cost_impact": 0
  },
  {
    "id": "RFI-164",
    "title": "Anchor bolt projection tolerances — pad B",
    "discipline": "Structural",
    "status": "Answered",
    "bic": "GC",
    "submitted": "2026-03-01",
    "required": "2026-03-01",
    "age": 56,
    "priority": "Low",
    "submitter": "K. Nguyen",
    "cost_impact": 0
  },
  {
    "id": "RFI-163",
    "title": "Erection sequence bay 8 — NE",
    "discipline": "Decking",
    "status": "Closed",
    "bic": "Owner",
    "submitted": "2026-02--6",
    "required": "2026-02--6",
    "age": 63,
    "priority": "Medium",
    "submitter": "S. Reyes",
    "cost_impact": 18200
  },
  {
    "id": "RFI-162",
    "title": "Bolt pattern on roof framing",
    "discipline": "Structural",
    "status": "Under Review",
    "bic": "Architect",
    "submitted": "2026-04-23",
    "required": "2026-04-23",
    "age": 6,
    "priority": "Critical",
    "submitter": "J. Patel",
    "cost_impact": 0
  },
  {
    "id": "RFI-161",
    "title": "Anchor bolt projection tolerances — pad F",
    "discipline": "Decking",
    "status": "Closed",
    "bic": "Engineer",
    "submitted": "2026-03--6",
    "required": "2026-03--6",
    "age": 35,
    "priority": "High",
    "submitter": "M. Ortega",
    "cost_impact": 0
  },
  {
    "id": "RFI-160",
    "title": "Field weld access — GL E/11",
    "discipline": "Misc Metals",
    "status": "Closed",
    "bic": "Contractor",
    "submitted": "2026-04-09",
    "required": "2026-04-09",
    "age": 20,
    "priority": "Medium",
    "submitter": "K. Nguyen",
    "cost_impact": 0
  },
  {
    "id": "RFI-159",
    "title": "Girt spacing clarification — bay 7",
    "discipline": "Anchor Bolts",
    "status": "Under Review",
    "bic": "Engineer",
    "submitted": "2026-04-23",
    "required": "2026-04-23",
    "age": 6,
    "priority": "Medium",
    "submitter": "D. Walsh",
    "cost_impact": 0
  },
  {
    "id": "RFI-158",
    "title": "Slip-critical bolt torque verification",
    "discipline": "Connections",
    "status": "Closed",
    "bic": "Contractor",
    "submitted": "2026-03--3",
    "required": "2026-03--3",
    "age": 32,
    "priority": "Low",
    "submitter": "K. Nguyen",
    "cost_impact": 21200
  },
  {
    "id": "RFI-157",
    "title": "Column orientation flip — GL B/4",
    "discipline": "Connections",
    "status": "Closed",
    "bic": "Owner",
    "submitted": "2026-03--11",
    "required": "2026-03--11",
    "age": 40,
    "priority": "Medium",
    "submitter": "R. Kovac",
    "cost_impact": 0
  },
  {
    "id": "RFI-156",
    "title": "Edge distance on shear connection",
    "discipline": "Stairs",
    "status": "Answered",
    "bic": "Engineer",
    "submitted": "2026-03--23",
    "required": "2026-03--23",
    "age": 52,
    "priority": "Medium",
    "submitter": "J. Patel",
    "cost_impact": 0
  },
  {
    "id": "RFI-155",
    "title": "Field weld access — GL F/4",
    "discipline": "Stairs",
    "status": "Open",
    "bic": "Architect",
    "submitted": "2026-04-19",
    "required": "2026-04-19",
    "age": 10,
    "priority": "High",
    "submitter": "R. Kovac",
    "cost_impact": 0
  },
  {
    "id": "RFI-154",
    "title": "Column orientation flip — GL B/1",
    "discipline": "Connections",
    "status": "Under Review",
    "bic": "Contractor",
    "submitted": "2026-04-21",
    "required": "2026-04-21",
    "age": 8,
    "priority": "Medium",
    "submitter": "D. Walsh",
    "cost_impact": 8000
  },
  {
    "id": "RFI-153",
    "title": "Embed plate layout at loading dock — clarification",
    "discipline": "Stairs",
    "status": "Closed",
    "bic": "Owner",
    "submitted": "2026-03--20",
    "required": "2026-03--20",
    "age": 49,
    "priority": "Medium",
    "submitter": "D. Walsh",
    "cost_impact": 0
  },
  {
    "id": "RFI-152",
    "title": "Shear tab thickness on GL B/12",
    "discipline": "Connections",
    "status": "Answered",
    "bic": "Engineer",
    "submitted": "2026-03--21",
    "required": "2026-03--21",
    "age": 50,
    "priority": "High",
    "submitter": "J. Patel",
    "cost_impact": 24400
  },
  {
    "id": "RFI-151",
    "title": "Camber on W21x76 at span 2",
    "discipline": "Anchor Bolts",
    "status": "Closed",
    "bic": "Engineer",
    "submitted": "2026-03--9",
    "required": "2026-03--9",
    "age": 38,
    "priority": "High",
    "submitter": "M. Ortega",
    "cost_impact": 0
  },
  {
    "id": "RFI-150",
    "title": "Baseplate grout thickness",
    "discipline": "Structural",
    "status": "Closed",
    "bic": "Owner",
    "submitted": "2026-03--5",
    "required": "2026-03--5",
    "age": 34,
    "priority": "Medium",
    "submitter": "S. Reyes",
    "cost_impact": 0
  },
  {
    "id": "RFI-149",
    "title": "Moment connection detail at mezzanine",
    "discipline": "Stairs",
    "status": "Answered",
    "bic": "Contractor",
    "submitted": "2026-03--17",
    "required": "2026-03--17",
    "age": 46,
    "priority": "Low",
    "submitter": "M. Ortega",
    "cost_impact": 0
  },
  {
    "id": "RFI-148",
    "title": "Bracing connection HSS21x{s}x76",
    "discipline": "Anchor Bolts",
    "status": "Closed",
    "bic": "Owner",
    "submitted": "2026-03--26",
    "required": "2026-03--26",
    "age": 55,
    "priority": "Critical",
    "submitter": "A. Chen",
    "cost_impact": 12400
  },
  {
    "id": "RFI-147",
    "title": "Column base plate anchor bolt pattern — GL B/9",
    "discipline": "Connections",
    "status": "Answered",
    "bic": "GC",
    "submitted": "2026-02--3",
    "required": "2026-02--3",
    "age": 60,
    "priority": "Critical",
    "submitter": "S. Reyes",
    "cost_impact": 0
  },
  {
    "id": "RFI-146",
    "title": "Girt spacing clarification — bay 4",
    "discipline": "Stairs",
    "status": "Closed",
    "bic": "Owner",
    "submitted": "2026-04-10",
    "required": "2026-04-10",
    "age": 19,
    "priority": "Low",
    "submitter": "L. Haines",
    "cost_impact": 15700
  },
  {
    "id": "RFI-145",
    "title": "Column splice location — GL A",
    "discipline": "Stairs",
    "status": "Closed",
    "bic": "GC",
    "submitted": "2026-03--22",
    "required": "2026-03--22",
    "age": 51,
    "priority": "Critical",
    "submitter": "M. Ortega",
    "cost_impact": 7500
  },
  {
    "id": "RFI-144",
    "title": "Moment connection detail at mezzanine",
    "discipline": "Misc Metals",
    "status": "Closed",
    "bic": "Owner",
    "submitted": "2026-03--2",
    "required": "2026-03--2",
    "age": 59,
    "priority": "Low",
    "submitter": "J. Patel",
    "cost_impact": 0
  },
  {
    "id": "RFI-143",
    "title": "Field weld access — GL H/11",
    "discipline": "Stairs",
    "status": "Closed",
    "bic": "Engineer",
    "submitted": "2026-03--11",
    "required": "2026-03--11",
    "age": 40,
    "priority": "High",
    "submitter": "K. Nguyen",
    "cost_impact": 0
  },
  {
    "id": "RFI-142",
    "title": "Bracing connection HSS16x{s}x40",
    "discipline": "Decking",
    "status": "Closed",
    "bic": "GC",
    "submitted": "2026-03--2",
    "required": "2026-03--2",
    "age": 31,
    "priority": "Critical",
    "submitter": "R. Kovac",
    "cost_impact": 22300
  },
  {
    "id": "RFI-141",
    "title": "Column orientation flip — GL E/11",
    "discipline": "Decking",
    "status": "Closed",
    "bic": "Architect",
    "submitted": "2026-03--18",
    "required": "2026-03--18",
    "age": 47,
    "priority": "Low",
    "submitter": "R. Kovac",
    "cost_impact": 0
  },
  {
    "id": "RFI-140",
    "title": "Camber on W18x62 at span 7",
    "discipline": "Anchor Bolts",
    "status": "Under Review",
    "bic": "Architect",
    "submitted": "2026-04-04",
    "required": "2026-04-04",
    "age": 25,
    "priority": "High",
    "submitter": "K. Nguyen",
    "cost_impact": 0
  },
  {
    "id": "RFI-139",
    "title": "Slip-critical bolt torque verification",
    "discipline": "Stairs",
    "status": "Answered",
    "bic": "GC",
    "submitted": "2026-03--21",
    "required": "2026-03--21",
    "age": 50,
    "priority": "Medium",
    "submitter": "D. Walsh",
    "cost_impact": 0
  },
  {
    "id": "RFI-138",
    "title": "Galvanized coating thickness on handrails",
    "discipline": "Connections",
    "status": "Closed",
    "bic": "GC",
    "submitted": "2026-02--5",
    "required": "2026-02--5",
    "age": 62,
    "priority": "Critical",
    "submitter": "S. Reyes",
    "cost_impact": 0
  },
  {
    "id": "RFI-137",
    "title": "Bracing connection HSS12x{s}x22",
    "discipline": "Structural",
    "status": "Closed",
    "bic": "GC",
    "submitted": "2026-03--18",
    "required": "2026-03--18",
    "age": 47,
    "priority": "High",
    "submitter": "M. Ortega",
    "cost_impact": 0
  },
  {
    "id": "RFI-136",
    "title": "Column base plate anchor bolt pattern — GL F/2",
    "discipline": "Anchor Bolts",
    "status": "Answered",
    "bic": "Engineer",
    "submitted": "2026-03--12",
    "required": "2026-03--12",
    "age": 41,
    "priority": "Critical",
    "submitter": "S. Reyes",
    "cost_impact": 20500
  },
  {
    "id": "RFI-135",
    "title": "Stair stringer camber on Stair 1",
    "discipline": "Stairs",
    "status": "Under Review",
    "bic": "Owner",
    "submitted": "2026-04-10",
    "required": "2026-04-10",
    "age": 19,
    "priority": "Low",
    "submitter": "M. Ortega",
    "cost_impact": 5000
  },
  {
    "id": "RFI-134",
    "title": "Weld inspection access — N column line",
    "discipline": "Misc Metals",
    "status": "Closed",
    "bic": "Architect",
    "submitted": "2026-03--26",
    "required": "2026-03--26",
    "age": 55,
    "priority": "High",
    "submitter": "R. Kovac",
    "cost_impact": 0
  },
  {
    "id": "RFI-133",
    "title": "Girt spacing clarification — bay 1",
    "discipline": "Decking",
    "status": "Closed",
    "bic": "GC",
    "submitted": "2026-03--12",
    "required": "2026-03--12",
    "age": 41,
    "priority": "Low",
    "submitter": "L. Haines",
    "cost_impact": 18100
  },
  {
    "id": "RFI-132",
    "title": "Bracing connection HSS27x{s}x40",
    "discipline": "Misc Metals",
    "status": "Open",
    "bic": "Contractor",
    "submitted": "2026-04-22",
    "required": "2026-04-22",
    "age": 7,
    "priority": "Medium",
    "submitter": "S. Reyes",
    "cost_impact": 0
  },
  {
    "id": "RFI-131",
    "title": "Slip-critical bolt torque verification",
    "discipline": "Stairs",
    "status": "Answered",
    "bic": "Architect",
    "submitted": "2026-02--6",
    "required": "2026-02--6",
    "age": 63,
    "priority": "High",
    "submitter": "S. Reyes",
    "cost_impact": 0
  },
  {
    "id": "RFI-130",
    "title": "Camber on W14x50 at span 6",
    "discipline": "Misc Metals",
    "status": "Answered",
    "bic": "Architect",
    "submitted": "2026-03-01",
    "required": "2026-03-01",
    "age": 56,
    "priority": "Low",
    "submitter": "M. Ortega",
    "cost_impact": 2400
  },
  {
    "id": "RFI-129",
    "title": "Field weld access — GL C/2",
    "discipline": "Connections",
    "status": "Closed",
    "bic": "Owner",
    "submitted": "2026-04-07",
    "required": "2026-04-07",
    "age": 22,
    "priority": "Medium",
    "submitter": "J. Patel",
    "cost_impact": 7100
  },
  {
    "id": "RFI-128",
    "title": "Column base plate anchor bolt pattern — GL F/11",
    "discipline": "Misc Metals",
    "status": "Answered",
    "bic": "Contractor",
    "submitted": "2026-03--9",
    "required": "2026-03--9",
    "age": 38,
    "priority": "Medium",
    "submitter": "J. Patel",
    "cost_impact": 300
  },
  {
    "id": "RFI-127",
    "title": "Stair stringer camber on Stair 5",
    "discipline": "Decking",
    "status": "Open",
    "bic": "Owner",
    "submitted": "2026-04-24",
    "required": "2026-04-24",
    "age": 5,
    "priority": "High",
    "submitter": "K. Nguyen",
    "cost_impact": 0
  },
  {
    "id": "RFI-126",
    "title": "Galvanized coating thickness on handrails",
    "discipline": "Connections",
    "status": "Answered",
    "bic": "Contractor",
    "submitted": "2026-03--4",
    "required": "2026-03--4",
    "age": 33,
    "priority": "Medium",
    "submitter": "M. Ortega",
    "cost_impact": 0
  },
  {
    "id": "RFI-125",
    "title": "Field weld access — GL F/5",
    "discipline": "Stairs",
    "status": "Answered",
    "bic": "Owner",
    "submitted": "2026-03--13",
    "required": "2026-03--13",
    "age": 42,
    "priority": "High",
    "submitter": "K. Nguyen",
    "cost_impact": 0
  },
  {
    "id": "RFI-124",
    "title": "Anchor bolt projection tolerances — pad G",
    "discipline": "Stairs",
    "status": "Answered",
    "bic": "Owner",
    "submitted": "2026-04-22",
    "required": "2026-04-22",
    "age": 7,
    "priority": "Medium",
    "submitter": "A. Chen",
    "cost_impact": 0
  },
  {
    "id": "RFI-123",
    "title": "Girt spacing clarification — bay 8",
    "discipline": "Connections",
    "status": "Answered",
    "bic": "Contractor",
    "submitted": "2026-04-09",
    "required": "2026-04-09",
    "age": 20,
    "priority": "High",
    "submitter": "K. Nguyen",
    "cost_impact": 4900
  },
  {
    "id": "RFI-122",
    "title": "Bracing connection HSS27x{s}x62",
    "discipline": "Anchor Bolts",
    "status": "Closed",
    "bic": "Owner",
    "submitted": "2026-03--3",
    "required": "2026-03--3",
    "age": 32,
    "priority": "Low",
    "submitter": "M. Ortega",
    "cost_impact": 0
  },
  {
    "id": "RFI-121",
    "title": "Camber on W14x40 at span 9",
    "discipline": "Stairs",
    "status": "Answered",
    "bic": "Architect",
    "submitted": "2026-04-10",
    "required": "2026-04-10",
    "age": 19,
    "priority": "High",
    "submitter": "A. Chen",
    "cost_impact": 17400
  },
  {
    "id": "RFI-120",
    "title": "Column orientation flip — GL E/10",
    "discipline": "Decking",
    "status": "Closed",
    "bic": "Owner",
    "submitted": "2026-04-04",
    "required": "2026-04-04",
    "age": 25,
    "priority": "High",
    "submitter": "D. Walsh",
    "cost_impact": 0
  },
  {
    "id": "RFI-119",
    "title": "Baseplate grout thickness",
    "discipline": "Stairs",
    "status": "Closed",
    "bic": "Owner",
    "submitted": "2026-03--17",
    "required": "2026-03--17",
    "age": 46,
    "priority": "High",
    "submitter": "A. Chen",
    "cost_impact": 7200
  },
  {
    "id": "RFI-118",
    "title": "HSS brace orientation on canopy frame bay 10",
    "discipline": "Stairs",
    "status": "Answered",
    "bic": "Contractor",
    "submitted": "2026-02--3",
    "required": "2026-02--3",
    "age": 60,
    "priority": "Low",
    "submitter": "K. Nguyen",
    "cost_impact": 6500
  },
  {
    "id": "RFI-117",
    "title": "Column orientation flip — GL G/3",
    "discipline": "Structural",
    "status": "Answered",
    "bic": "Architect",
    "submitted": "2026-03--26",
    "required": "2026-03--26",
    "age": 55,
    "priority": "Critical",
    "submitter": "J. Patel",
    "cost_impact": 0
  },
  {
    "id": "RFI-116",
    "title": "Slip-critical bolt torque verification",
    "discipline": "Structural",
    "status": "Closed",
    "bic": "Architect",
    "submitted": "2026-03--25",
    "required": "2026-03--25",
    "age": 54,
    "priority": "High",
    "submitter": "R. Kovac",
    "cost_impact": 0
  },
  {
    "id": "RFI-115",
    "title": "Erection sequence bay 2 — W",
    "discipline": "Connections",
    "status": "Closed",
    "bic": "Engineer",
    "submitted": "2026-03-01",
    "required": "2026-03-01",
    "age": 56,
    "priority": "Critical",
    "submitter": "M. Ortega",
    "cost_impact": 10000
  },
  {
    "id": "RFI-114",
    "title": "Paint holiday at field splice",
    "discipline": "Decking",
    "status": "Open",
    "bic": "Contractor",
    "submitted": "2026-04-18",
    "required": "2026-04-18",
    "age": 11,
    "priority": "High",
    "submitter": "S. Reyes",
    "cost_impact": 13200
  },
  {
    "id": "RFI-113",
    "title": "Shear tab thickness on GL C/8",
    "discipline": "Connections",
    "status": "Answered",
    "bic": "Engineer",
    "submitted": "2026-02--7",
    "required": "2026-02--7",
    "age": 64,
    "priority": "Critical",
    "submitter": "K. Nguyen",
    "cost_impact": 13900
  },
  {
    "id": "RFI-112",
    "title": "Moment connection detail at mezzanine",
    "discipline": "Misc Metals",
    "status": "Closed",
    "bic": "GC",
    "submitted": "2026-03--17",
    "required": "2026-03--17",
    "age": 46,
    "priority": "High",
    "submitter": "D. Walsh",
    "cost_impact": 0
  },
  {
    "id": "RFI-111",
    "title": "Anchor bolt projection tolerances — pad C",
    "discipline": "Decking",
    "status": "Closed",
    "bic": "Engineer",
    "submitted": "2026-03--17",
    "required": "2026-03--17",
    "age": 46,
    "priority": "Low",
    "submitter": "K. Nguyen",
    "cost_impact": 13300
  },
  {
    "id": "RFI-110",
    "title": "Girt spacing clarification — bay 6",
    "discipline": "Structural",
    "status": "Closed",
    "bic": "Engineer",
    "submitted": "2026-03--3",
    "required": "2026-03--3",
    "age": 32,
    "priority": "Medium",
    "submitter": "D. Walsh",
    "cost_impact": 5600
  },
  {
    "id": "RFI-109",
    "title": "Galvanized coating thickness on handrails",
    "discipline": "Stairs",
    "status": "Closed",
    "bic": "Engineer",
    "submitted": "2026-04-03",
    "required": "2026-04-03",
    "age": 26,
    "priority": "High",
    "submitter": "K. Nguyen",
    "cost_impact": 0
  }
];

window.MOCK_WORK_PACKAGES = [
  {
    "id": "WP-050",
    "name": "PAD A: MAIN STEEL",
    "phase": "Erection",
    "status": "In Progress",
    "tons": 54.5,
    "sheets": 15,
    "released_pct": 100,
    "discipline": "Anchor Bolts",
    "bic": "Contractor",
    "start": "2026-04-05",
    "due": "2026-04-15",
    "progress": 35
  },
  {
    "id": "WP-049",
    "name": "PAD A: CANOPIES",
    "phase": "Detailing",
    "status": "In Progress",
    "tons": 96.2,
    "sheets": 7,
    "released_pct": 100,
    "discipline": "Connections",
    "bic": "Architect",
    "start": "2026-03-10",
    "due": "2026-04-12",
    "progress": 19
  },
  {
    "id": "WP-048",
    "name": "PAD B: MAIN STEEL & CANOPIES",
    "phase": "Detailing",
    "status": "In Progress",
    "tons": 52.1,
    "sheets": 5,
    "released_pct": 100,
    "discipline": "Misc Metals",
    "bic": "Architect",
    "start": "2026-03-25",
    "due": "2026-03-13",
    "progress": 80
  },
  {
    "id": "WP-047",
    "name": "PAD C: MAIN STEEL",
    "phase": "Delivery",
    "status": "Complete",
    "tons": 8.9,
    "sheets": 16,
    "released_pct": 100,
    "discipline": "Structural",
    "bic": "Engineer",
    "start": "2026-02-22",
    "due": "2026-03-22",
    "progress": 100
  },
  {
    "id": "WP-046",
    "name": "PAD C: CANOPIES",
    "phase": "Detailing",
    "status": "In Progress",
    "tons": 74.7,
    "sheets": 24,
    "released_pct": 100,
    "discipline": "Structural",
    "bic": "GC",
    "start": "2026-02-23",
    "due": "2026-05-15",
    "progress": 61
  },
  {
    "id": "WP-045",
    "name": "PAD D: MAIN STEEL",
    "phase": "Fabrication",
    "status": "In Progress",
    "tons": 105.1,
    "sheets": 7,
    "released_pct": 100,
    "discipline": "Misc Metals",
    "bic": "Owner",
    "start": "2026-01-25",
    "due": "2026-03-11",
    "progress": 77
  },
  {
    "id": "WP-044",
    "name": "SHOP A: MAIN STEEL",
    "phase": "Detailing",
    "status": "On Hold",
    "tons": 82.9,
    "sheets": 8,
    "released_pct": 100,
    "discipline": "Structural",
    "bic": "Engineer",
    "start": "2026-03-26",
    "due": "2026-04-02",
    "progress": 58
  },
  {
    "id": "WP-043",
    "name": "SHOP A: CANOPIES",
    "phase": "Detailing",
    "status": "On Hold",
    "tons": 104.9,
    "sheets": 24,
    "released_pct": 100,
    "discipline": "Structural",
    "bic": "GC",
    "start": "2026-03-15",
    "due": "2026-05-17",
    "progress": 38
  },
  {
    "id": "WP-042",
    "name": "SHOP A: ANCHOR BOLTS",
    "phase": "Delivery",
    "status": "In Progress",
    "tons": 144.4,
    "sheets": 23,
    "released_pct": 100,
    "discipline": "Anchor Bolts",
    "bic": "Engineer",
    "start": "2026-02-20",
    "due": "2026-05-27",
    "progress": 81
  },
  {
    "id": "WP-041",
    "name": "SHOP B: MAIN STEEL",
    "phase": "Detailing",
    "status": "In Progress",
    "tons": 7.3,
    "sheets": 18,
    "released_pct": 100,
    "discipline": "Misc Metals",
    "bic": "Owner",
    "start": "2026-03-03",
    "due": "2026-03-08",
    "progress": 16
  },
  {
    "id": "WP-040",
    "name": "SHOP B: CANOPIES",
    "phase": "Fabrication",
    "status": "In Progress",
    "tons": 57.8,
    "sheets": 9,
    "released_pct": 100,
    "discipline": "Connections",
    "bic": "Contractor",
    "start": "2026-04-27",
    "due": "2026-05-19",
    "progress": 52
  },
  {
    "id": "WP-039",
    "name": "SHOP C: MAIN STEEL",
    "phase": "Delivery",
    "status": "In Progress",
    "tons": 19.1,
    "sheets": 10,
    "released_pct": 100,
    "discipline": "Connections",
    "bic": "GC",
    "start": "2026-01-06",
    "due": "2026-05-26",
    "progress": 45
  },
  {
    "id": "WP-038",
    "name": "SHOP C: CANOPIES",
    "phase": "Erection",
    "status": "In Progress",
    "tons": 126.6,
    "sheets": 20,
    "released_pct": 100,
    "discipline": "Misc Metals",
    "bic": "Engineer",
    "start": "2026-03-27",
    "due": "2026-05-16",
    "progress": 51
  },
  {
    "id": "WP-037",
    "name": "SHOP C: FRAMING",
    "phase": "Delivery",
    "status": "On Hold",
    "tons": 80.5,
    "sheets": 23,
    "released_pct": 100,
    "discipline": "Anchor Bolts",
    "bic": "Owner",
    "start": "2026-01-02",
    "due": "2026-03-23",
    "progress": 36
  },
  {
    "id": "WP-036",
    "name": "SHOP D: MAIN STEEL",
    "phase": "Fabrication",
    "status": "In Progress",
    "tons": 8.9,
    "sheets": 4,
    "released_pct": 100,
    "discipline": "Misc Metals",
    "bic": "Engineer",
    "start": "2026-02-20",
    "due": "2026-03-12",
    "progress": 41
  },
  {
    "id": "WP-035",
    "name": "SHOP D: CANOPIES",
    "phase": "Fabrication",
    "status": "In Progress",
    "tons": 99.3,
    "sheets": 11,
    "released_pct": 100,
    "discipline": "Anchor Bolts",
    "bic": "Owner",
    "start": "2026-01-16",
    "due": "2026-03-23",
    "progress": 13
  },
  {
    "id": "WP-034",
    "name": "SHOP D: FRAMING",
    "phase": "Detailing",
    "status": "In Progress",
    "tons": 24.9,
    "sheets": 10,
    "released_pct": 100,
    "discipline": "Structural",
    "bic": "Contractor",
    "start": "2026-01-12",
    "due": "2026-05-18",
    "progress": 69
  },
  {
    "id": "WP-033",
    "name": "SHOP E: MAIN STEEL",
    "phase": "Fabrication",
    "status": "In Progress",
    "tons": 28.6,
    "sheets": 13,
    "released_pct": 100,
    "discipline": "Misc Metals",
    "bic": "Contractor",
    "start": "2026-04-25",
    "due": "2026-03-06",
    "progress": 30
  },
  {
    "id": "WP-032",
    "name": "SHOP E: CANOPIES",
    "phase": "Erection",
    "status": "Not Started",
    "tons": 103.7,
    "sheets": 16,
    "released_pct": 0,
    "discipline": "Anchor Bolts",
    "bic": "Contractor",
    "start": "2026-03-28",
    "due": "2026-04-17",
    "progress": 0
  },
  {
    "id": "WP-031",
    "name": "STAIR 1 STRUCTURAL",
    "phase": "Fabrication",
    "status": "Complete",
    "tons": 128.1,
    "sheets": 19,
    "released_pct": 100,
    "discipline": "Connections",
    "bic": "Contractor",
    "start": "2026-02-23",
    "due": "2026-03-03",
    "progress": 100
  },
  {
    "id": "WP-030",
    "name": "STAIR 2 STRUCTURAL",
    "phase": "Erection",
    "status": "In Progress",
    "tons": 25.3,
    "sheets": 12,
    "released_pct": 100,
    "discipline": "Misc Metals",
    "bic": "Owner",
    "start": "2026-01-12",
    "due": "2026-03-13",
    "progress": 34
  },
  {
    "id": "WP-029",
    "name": "STAIR 3 STRUCTURAL",
    "phase": "Erection",
    "status": "In Progress",
    "tons": 32.2,
    "sheets": 5,
    "released_pct": 100,
    "discipline": "Connections",
    "bic": "Engineer",
    "start": "2026-02-08",
    "due": "2026-03-11",
    "progress": 90
  },
  {
    "id": "WP-028",
    "name": "MEZZANINE FRAMING: NORTH",
    "phase": "Erection",
    "status": "In Progress",
    "tons": 114.6,
    "sheets": 12,
    "released_pct": 100,
    "discipline": "Structural",
    "bic": "Contractor",
    "start": "2026-02-08",
    "due": "2026-04-11",
    "progress": 62
  },
  {
    "id": "WP-027",
    "name": "MEZZANINE FRAMING: SOUTH",
    "phase": "Fabrication",
    "status": "In Progress",
    "tons": 107.1,
    "sheets": 11,
    "released_pct": 100,
    "discipline": "Anchor Bolts",
    "bic": "GC",
    "start": "2026-01-27",
    "due": "2026-04-28",
    "progress": 63
  },
  {
    "id": "WP-026",
    "name": "ROOF DECK & PURLINS: BAY 1-3",
    "phase": "Delivery",
    "status": "In Progress",
    "tons": 83.3,
    "sheets": 5,
    "released_pct": 100,
    "discipline": "Connections",
    "bic": "Architect",
    "start": "2026-03-01",
    "due": "2026-05-13",
    "progress": 56
  },
  {
    "id": "WP-025",
    "name": "ROOF DECK & PURLINS: BAY 4-6",
    "phase": "Fabrication",
    "status": "In Progress",
    "tons": 43.2,
    "sheets": 25,
    "released_pct": 100,
    "discipline": "Anchor Bolts",
    "bic": "GC",
    "start": "2026-03-25",
    "due": "2026-03-14",
    "progress": 71
  },
  {
    "id": "WP-024",
    "name": "ROOF DECK & PURLINS: BAY 7-9",
    "phase": "Fabrication",
    "status": "In Progress",
    "tons": 55.2,
    "sheets": 25,
    "released_pct": 100,
    "discipline": "Connections",
    "bic": "Contractor",
    "start": "2026-03-25",
    "due": "2026-05-03",
    "progress": 31
  },
  {
    "id": "WP-023",
    "name": "CANOPY EXTENSIONS: WEST ENTRY",
    "phase": "Detailing",
    "status": "In Progress",
    "tons": 24.2,
    "sheets": 10,
    "released_pct": 100,
    "discipline": "Misc Metals",
    "bic": "GC",
    "start": "2026-01-21",
    "due": "2026-05-16",
    "progress": 56
  },
  {
    "id": "WP-022",
    "name": "CANOPY EXTENSIONS: EAST ENTRY",
    "phase": "Erection",
    "status": "In Progress",
    "tons": 115.2,
    "sheets": 8,
    "released_pct": 100,
    "discipline": "Anchor Bolts",
    "bic": "Architect",
    "start": "2026-01-15",
    "due": "2026-04-18",
    "progress": 28
  },
  {
    "id": "WP-021",
    "name": "HANDRAILS & GUARDS: PAD A-C",
    "phase": "Delivery",
    "status": "Complete",
    "tons": 12.6,
    "sheets": 23,
    "released_pct": 100,
    "discipline": "Anchor Bolts",
    "bic": "GC",
    "start": "2026-02-03",
    "due": "2026-04-23",
    "progress": 100
  },
  {
    "id": "WP-020",
    "name": "HANDRAILS & GUARDS: SHOPS",
    "phase": "Erection",
    "status": "Complete",
    "tons": 114,
    "sheets": 5,
    "released_pct": 100,
    "discipline": "Structural",
    "bic": "GC",
    "start": "2026-04-28",
    "due": "2026-04-27",
    "progress": 100
  },
  {
    "id": "WP-019",
    "name": "LOADING DOCK: EMBEDS & PLATES",
    "phase": "Delivery",
    "status": "In Progress",
    "tons": 103.5,
    "sheets": 11,
    "released_pct": 100,
    "discipline": "Structural",
    "bic": "Engineer",
    "start": "2026-03-07",
    "due": "2026-04-08",
    "progress": 20
  }
];

window.MOCK_DELIVERIES = [
  {
    "id": "DEL-040",
    "wp": "WP-045",
    "description": "Mezzanine beams north wing (partial)",
    "scheduled": "2026-04-14",
    "status": "Scheduled",
    "tons": 9.5,
    "pieces": 147,
    "truck": "FLATBED-7",
    "carrier": "InHouse",
    "yard": "Shop 1"
  },
  {
    "id": "DEL-039",
    "wp": "WP-037",
    "description": "Final connection material",
    "scheduled": "2026-04-19",
    "status": "Loading",
    "tons": 8.1,
    "pieces": 20,
    "truck": "FLATBED-5",
    "carrier": "MidwestFreight",
    "yard": "Shop 1"
  },
  {
    "id": "DEL-038",
    "wp": "WP-018",
    "description": "Stair stringers + landings",
    "scheduled": "2026-04-15",
    "status": "In Transit",
    "tons": 2.2,
    "pieces": 48,
    "truck": "FLATBED-2",
    "carrier": "EagleTransport",
    "yard": "Shop 2"
  },
  {
    "id": "DEL-037",
    "wp": "WP-032",
    "description": "Final connection material",
    "scheduled": "2026-04-10",
    "status": "Delivered",
    "tons": 28,
    "pieces": 60,
    "truck": "FLATBED-5",
    "carrier": "LoneStarHaul",
    "yard": "Shop 3",
    "delivered_at": "2026-04-10 10:53"
  },
  {
    "id": "DEL-036",
    "wp": "WP-028",
    "description": "Mezzanine beams north wing (partial)",
    "scheduled": "2026-04-27",
    "status": "Partial",
    "tons": 15.5,
    "pieces": 182,
    "truck": "BOX-1",
    "carrier": "EagleTransport",
    "yard": "Shop 2"
  },
  {
    "id": "DEL-035",
    "wp": "WP-022",
    "description": "Handrails bundle",
    "scheduled": "2026-04-26",
    "status": "Rejected",
    "tons": 15.9,
    "pieces": 154,
    "truck": "FLATBED-4",
    "carrier": "LoneStarHaul",
    "yard": "Shop 2"
  },
  {
    "id": "DEL-034",
    "wp": "WP-040",
    "description": "Loading dock embeds + anchor plates",
    "scheduled": "2026-04-29",
    "status": "Overdue",
    "tons": 22.9,
    "pieces": 172,
    "truck": "STEP-DECK-2",
    "carrier": "EagleTransport",
    "yard": "Shop 2"
  },
  {
    "id": "DEL-033",
    "wp": "WP-025",
    "description": "Pad B canopy beams + girts (load 1 of 3)",
    "scheduled": "2026-04-19",
    "status": "Scheduled",
    "tons": 26.8,
    "pieces": 36,
    "truck": "STEP-DECK-2",
    "carrier": "InHouse",
    "yard": "Shop 1"
  },
  {
    "id": "DEL-032",
    "wp": "WP-018",
    "description": "Pad C canopy beams + girts (load 2 of 3)",
    "scheduled": "2026-04-26",
    "status": "Overdue",
    "tons": 28,
    "pieces": 33,
    "truck": "BOX-1",
    "carrier": "EagleTransport",
    "yard": "Shop 2"
  },
  {
    "id": "DEL-031",
    "wp": "WP-033",
    "description": "Mezzanine beams north wing (partial)",
    "scheduled": "2026-04-20",
    "status": "Rejected",
    "tons": 29.3,
    "pieces": 159,
    "truck": "FLATBED-5",
    "carrier": "EagleTransport",
    "yard": "Shop 3"
  },
  {
    "id": "DEL-030",
    "wp": "WP-022",
    "description": "Field weld consumables + inspection kit",
    "scheduled": "2026-04-12",
    "status": "Delivered",
    "tons": 31.6,
    "pieces": 194,
    "truck": "FLATBED-7",
    "carrier": "LoneStarHaul",
    "yard": "Shop 1",
    "delivered_at": "2026-04-12 12:29"
  },
  {
    "id": "DEL-029",
    "wp": "WP-023",
    "description": "Mezzanine beams north wing (partial)",
    "scheduled": "2026-04-27",
    "status": "Delivered",
    "tons": 16.6,
    "pieces": 195,
    "truck": "BOX-1",
    "carrier": "MidwestFreight",
    "yard": "Shop 1",
    "delivered_at": "2026-04-27 07:14"
  },
  {
    "id": "DEL-028",
    "wp": "WP-021",
    "description": "Shop E canopy columns + tubes",
    "scheduled": "2026-04-11",
    "status": "Overdue",
    "tons": 17.6,
    "pieces": 95,
    "truck": "FLATBED-7",
    "carrier": "LoneStarHaul",
    "yard": "Shop 3"
  },
  {
    "id": "DEL-027",
    "wp": "WP-045",
    "description": "Final connection material",
    "scheduled": "2026-04-28",
    "status": "Rejected",
    "tons": 18.1,
    "pieces": 98,
    "truck": "FLATBED-4",
    "carrier": "MidwestFreight",
    "yard": "Shop 1"
  },
  {
    "id": "DEL-026",
    "wp": "WP-034",
    "description": "Pad E canopy beams + girts (load 3 of 3)",
    "scheduled": "2026-04-19",
    "status": "Scheduled",
    "tons": 3.5,
    "pieces": 197,
    "truck": "BOX-3",
    "carrier": "LoneStarHaul",
    "yard": "Shop 1"
  },
  {
    "id": "DEL-025",
    "wp": "WP-045",
    "description": "HSS bracing bundle 5",
    "scheduled": "2026-04-20",
    "status": "Partial",
    "tons": 7.9,
    "pieces": 156,
    "truck": "BOX-3",
    "carrier": "MidwestFreight",
    "yard": "Shop 1"
  },
  {
    "id": "DEL-024",
    "wp": "WP-038",
    "description": "Mezzanine beams north wing (partial)",
    "scheduled": "2026-04-21",
    "status": "Rejected",
    "tons": 33.9,
    "pieces": 71,
    "truck": "BOX-3",
    "carrier": "EagleTransport",
    "yard": "Shop 1"
  },
  {
    "id": "DEL-023",
    "wp": "WP-036",
    "description": "Column splice plates + bolts",
    "scheduled": "2026-04-27",
    "status": "Rejected",
    "tons": 4,
    "pieces": 197,
    "truck": "FLATBED-4",
    "carrier": "InHouse",
    "yard": "Shop 1"
  },
  {
    "id": "DEL-022",
    "wp": "WP-043",
    "description": "Main steel W-sections pad A",
    "scheduled": "2026-04-22",
    "status": "Partial",
    "tons": 26.2,
    "pieces": 121,
    "truck": "FLATBED-5",
    "carrier": "LoneStarHaul",
    "yard": "Shop 1"
  },
  {
    "id": "DEL-021",
    "wp": "WP-045",
    "description": "Roof deck bundles + purlins bay 1-7",
    "scheduled": "2026-04-10",
    "status": "Delivered",
    "tons": 2.7,
    "pieces": 34,
    "truck": "BOX-3",
    "carrier": "LoneStarHaul",
    "yard": "Shop 2",
    "delivered_at": "2026-04-10 13:23"
  },
  {
    "id": "DEL-020",
    "wp": "WP-026",
    "description": "Handrails bundle",
    "scheduled": "2026-04-12",
    "status": "In Transit",
    "tons": 30.9,
    "pieces": 191,
    "truck": "STEP-DECK-1",
    "carrier": "InHouse",
    "yard": "Shop 1"
  },
  {
    "id": "DEL-019",
    "wp": "WP-043",
    "description": "Pad C canopy beams + girts (load 3 of 3)",
    "scheduled": "2026-04-13",
    "status": "Rejected",
    "tons": 11.1,
    "pieces": 40,
    "truck": "FLATBED-7",
    "carrier": "EagleTransport",
    "yard": "Shop 3"
  }
];

window.MOCK_ALERTS = [
  { id: 1, severity: "critical", title: "Schedule variance — 84% elapsed, 61% progress", desc: "Verify WP status or update progress",       when: "4/20/2026",  ref: "25372" },
  { id: 2, severity: "warning",  title: "RFI-123 overdue (Connections)",                  desc: "Required by 2026-04-18 — BIC: GC",          when: "Yesterday",  ref: "RFI-123" },
  { id: 3, severity: "warning",  title: "3 unacknowledged drawing revisions",             desc: "101ABP103, 101ABP101, 101ABP102",           when: "Yesterday",  ref: "DRW-R1" },
  { id: 4, severity: "info",     title: "Delivery DEL-015 arrived at Shop 1",             desc: "4.2T signed for — M. Ortega",               when: "2d ago",     ref: "DEL-015" },
];

window.MOCK_QUICK_UPDATES = [
  { id: "q1", type: "wp",   label: "WP-043 progress",      from: "Updated 6d ago",  suggest: "Bump to 85%?" },
  { id: "q2", type: "rfi",  label: "RFI-124 response",     from: "Engineer pending", suggest: "Nudge engineer" },
  { id: "q3", type: "del",  label: "DEL-018 confirm time", from: "Loading today",    suggest: "Set ETA" },
];

window.MOCK_SPEND = [
  { month: "Oct", actual: 42000,  committed: 88000 },
  { month: "Nov", actual: 98000,  committed: 182000 },
  { month: "Dec", actual: 186000, committed: 284000 },
  { month: "Jan", actual: 284000, committed: 402000 },
  { month: "Feb", actual: 382000, committed: 524000 },
  { month: "Mar", actual: 498000, committed: 648000 },
  { month: "Apr", actual: 586000, committed: 756549 },
];
